### PR TITLE
update Envoy's SHA to latest, to implement SNI telemetry reports and policy checks 

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
to include the SNI inspecting method, for using SNI in telemetry and
policies

Signed-off-by: Vadim Eisenberg <vadime@il.ibm.com>

**What this PR does / why we need it**:
The PR is a prerequisite for https://github.com/istio/istio/issues/6810. It is required to extract SNI and to use it in telemetry reports and policy checks.

**Which issue this PR fixes** 
A prerequisite for https://github.com/istio/istio/issues/6810

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
@kyessenov Could you please merge this PR?

**Comment by kyessenov** [comment]
All repositories are locked, and can only be merged by admins. I'm not an
admin.

**Comment by vadimeisenbergibm** [comment]
@hklai Could you please merge this PR?

**Comment by costinm** [comment]
Please rebase to 1.0 ( I assume that's where you want it ) ?

**Comment by vadimeisenbergibm** [comment]
@costinm Done.

**Comment by hklai** [comment]
I don't think istio/istio#6810 is P0 for 1.0. should we even merge this at this point?

**Comment by vadimeisenbergibm** [comment]
@hklai I would really like to complete it this week. It is just one attribute to implement in istio-proxy, and it will upgrade egress traffic handling in Istio 1.0 significantly, since most of the egress traffic is TLS with SNI.

**Comment by vadimeisenbergibm** [comment]
@hklai Thanks, will do.

**Pull request merged**
