### PR TITLE
Send dynamic metadata as part of report calls

### PR DESCRIPTION
**Pull request by rshriram**
Envoy filters can add arbitrary attributes to dynamicMetadata. Its useful to log this as part of reports (envoy's gRPC access logs and normal access logs already print this info).

I am send the metadata as a dumb string (serialized form of envoy.api.v2.core.Metadata). Right now, there is no support in mixer for this, but an adapter wishing to utilize this can deserialize this info and log this info, thus providing the ability for third party codecs to log additional attributes as part of a connection.

Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by rshriram** [comment]
temporary fix for https://github.com/istio/istio/issues/9613 . At the moment, this should unblock the internal use case I have to stream custom attributes generated by internal codecs to mixer without having to fork Istio mixer filter code. Would be nice to have a cleaner solution.

**Comment by qiwzhang** [comment]
Only for tcp?   Just curious, why not Http?

**Comment by rshriram** [comment]
Oh I can do the same for HTTP as well.

**Comment by rshriram** [comment]
@qiwzhang updated to add dynamic metadata to http as well.

**Pull request merged**
