### PR TITLE
build: apply buildifer recommendations

### PR DESCRIPTION
**Pull request by kyessenov**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kyessenov** [comment]
No, there's no code change in this PR. Those tests are just extra flakey, especially when you run them together.

**Review by lei-tang — APPROVED** [review]

**Comment by kyessenov** [comment]
Looks like the flake became permanent...
/retest

**Pull request merged**
