### PR TITLE
add override indicator to functions - fixes MacOS build

### LINKED ISSUE #973: Build fails on MacOS
I'm unable to build proxy master (59ee751a68f26d5218adf2a12df0ccee9f1fa404) on MacOS High Sierra (10.10.13). Output:

```
ERROR: /Users/theganyo/dev/istio/src/istio.io/proxy/src/envoy/mixer/BUILD:23:1: C++ compilation of rule '//src/envoy/mixer:filter_lib' failed (Exit 1)
src/envoy/mixer/tcp_filter.cc:187:8: error: 'GetSourceIpPort' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  bool GetSourceIpPort(std::string* str_ip, int* port) const {
       ^
external/mixerclient_git/control/include/tcp/check_data.h:32:16: note: overridden virtual function is here
  virtual bool GetSourceIpPort(std::string* ip, int* port) const = 0;
               ^
src/envoy/mixer/tcp_filter.cc:191:8: error: 'GetSourceUser' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  bool GetSourceUser(std::string* user) const {
       ^
external/mixerclient_git/control/include/tcp/check_data.h:35:16: note: overridden virtual function is here
  virtual bool GetSourceUser(std::string* user) const = 0;
               ^
src/envoy/mixer/tcp_filter.cc:194:8: error: 'GetDestinationIpPort' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  bool GetDestinationIpPort(std::string* str_ip, int* port) const {
       ^
external/mixerclient_git/control/include/tcp/report_data.h:33:16: note: overridden virtual function is here
  virtual bool GetDestinationIpPort(std::string* ip, int* port) const = 0;
               ^
src/envoy/mixer/tcp_filter.cc:202:8: error: 'GetReportInfo' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  void GetReportInfo(
       ^
external/mixerclient_git/control/include/tcp/report_data.h:41:16: note: overridden virtual function is here
  virtual void GetReportInfo(ReportInfo* info) const = 0;
               ^
4 errors generated.
INFO: Elapsed time: 228.389s, Critical Path: 25.66s
FAILED: Build did NOT complete successfully
make: *** [build] Error 1
```

### PR DESCRIPTION
**Pull request by theganyo**
**What this PR does / why we need it**: Fixes build on MacOS 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #973

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by lizan** [comment]
Can you run script/check-style to make sure the source is formatted?

**Comment by theganyo** [comment]
No, it appears that a linux check-style binary is downloaded instead of MacOS. 

```
script/check-style
script/check-style: line 26: /Users/theganyo/clang/bin/clang-format: No such file or directory
Installing required clang-format 3.8.0 to /Users/theganyo/clang
Checking file format ...
script/check-style: line 41: /Users/theganyo/clang/bin/clang-format: cannot execute binary file
Could not run clang-format.```

**Comment by theganyo** [comment]
Ok, hopefully that fixes the issue. I'll open a new issue on the `script/check-style` script being linux-specific.

**Comment by theganyo** [comment]
I pushed the reformatted code.

**Pull request merged**
