### PR TITLE
[Cherry pick] "Add the support of bypassing JWT authn for CORS requests" to release 1.1

### LINKED ISSUE #2160: OPTION JWT authentication bypass not working
**Issue**
---
I have cross-site traffic going from app.service.net going to api.service.net.  The application is required to authenticate this traffic with istio via JWT.  However during the initial interaction OPTIONS is being forced to authenticate with istio.  Since OPTIONS commands do not include `Authentication` headers it fails with `401 unauthorized`.

As I understand it, the below issues/PRs are supposed to have fixed this issue:
#651 
#2139 
#2140 

Is there anything I am missing from these issues that is preventing me from properly configuring the bypass for OPTIONS or has this become an issue again?

I have listed my configuration and versions below.

**Configuration**
---

**Istio/Kubernetes Version**

```
[procyclinsur@P-428 core-api]$ istioctl version
version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}

[procyclinsur@P-428 core-api]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**JWT Policy**

* namespace: istio-system

```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: core-api-jwt-auth
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 443
  origins:
  - jwt:
      audiences:
      - 4i00tescmmXXXXXX6c1chlvhpq
      issuer: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX
      jwksUri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX/.well-known/jwks.json
  principalBinding: USE_ORIGIN
```

**ingress-gateway:**

* namespace: istio-system

istio-ingressgateway is default aside from being an AWS NLB as opposed to an AWS CLB.

**gateway**

* namespace: custom

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: core-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.service.net"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "api.service.net"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```

**virtual service** 

* namespace: custom

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: core-api-virtual-service
spec:
  hosts:
  - "api.service.net"
  gateways:
  - core-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: core-api-service
        port:
          number: 80
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
      allowHeaders:
        - content-type
        - authorization
      maxAge: 300s
      allowCredentials: false

### PR DESCRIPTION
**Pull request by lei-tang**
**What this PR does / why we need it**: this PR is for the issue https://github.com/istio/proxy/issues/2160. The two PRs related to "Add the support of bypassing JWT authn for CORS requests" are in the master branch but not in the release 1.1 branch. This PR cherry-picks the two PRs from master branch to release 1.1 branch.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2160 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by procyclinsur** [comment]
Can we get someone to restart the checks? It seems like there wasn't vms available to perform them so they failed?

**Comment by lei-tang** [comment]
I rebased the PR to latest release 1.1 and git pushed the PR to restart the presubmit checks.

**Comment by lei-tang** [comment]
The PR has passed all presubmit tests and is waiting for approvals from the reviewers.

**Comment by procyclinsur** [comment]
@duderino @rshriram @qiwzhang Can we get this approved for the 1.1 release?

**Comment by rshriram** [comment]
@lizan ?

**Comment by duderino** [comment]
@procyclinsur @lei-tang I need to push back more on 1.1.x PRs.  At this point attention should really shift to master and then 1.2.  So what are the implications of not merging this?

**Comment by procyclinsur** [comment]
> @procyclinsur @lei-tang I need to push back more on 1.1.x PRs. At this point attention should really shift to master and then 1.2. So what are the implications of not merging this?

@duderino Thank you for the response :smile:! It makes sense to concentrate on 1.2, and from a business standpoint (for me) it may not be completely necessary to have this merged into the 1.1 branch if 1.2 will be coming within the next month, and will contain these commits? 

The technical implications of not merging this commit are that Istio will continue to deny all traffic to cross-site jwt authenticated paths due to the preflight CORS request failing.  CORS requests by [specification](http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0) do not/should not contain authentication credentials.  Therefore the request is rejected before it even starts.

Also, I have been searching for documents describing policy for the Test and Release SIG, and have found nothing regarding release schedule.  Does Istio currently have a fixed release schedule?

**Comment by duderino** [comment]
@fpesce could you give this a security review?  It is in master and probably in 1.2

**Comment by fpesce** [comment]
Not a CORS expert.
/lgtm

**Pull request merged**
