### PR TITLE
test: set timeout

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Review by mandarjog — APPROVED** [review]
Lgtm

**Comment by bianpengyuan** [comment]
Looks like we got a bigger problem. Tsan stucks regardless of the timeout.

**Comment by kyessenov** [comment]
Shucks, I'll need to build TSan version to diagnose. If anyone has clang10, you can take over this, since it doesn't build on my clang8 (binary too big).

**Pull request merged**
