### PR TITLE
Remove pessimizing move.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Found with -Wpessimizing-move.

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Sigh, why did @qiwzhang's merge break `cla: yes` label? And how do I fix it?

**Comment by lizan** [comment]
@qiwzhang do not click "Update branch" if you are not the author of the PR, it will break CLA AFAIK. @PiotrSikora please merge your self (at your local working copy) and force push.

**Pull request merged**
