### PR TITLE
requesting to add myself as a reviewer/approver

### PR DESCRIPTION
**Pull request by kyessenov**
I have 39 commits in this repo.

### CODE REVIEW

**Comment by utka** [comment]
Is there official rule who can be added to OWNERS file?

**Comment by linsun** [comment]
I think we have a rule for WG leads to promote folks as owners.  However, for proxy repo, should it belong to networking WG?

**Comment by kyessenov** [comment]
Majority of additions in proxy are for policy, telemetry, and security functions. So I don't think this is a purely networking component.

**Comment by mandarjog** [comment]
The ownership is split across P&T and Networking. 
@rshriram @lizan please approve.

The owners file does need cleaning in proxy.

**Comment by lizan** [comment]
/lgtm
/approve

**Pull request merged**
