### PR TITLE
sync health_checkers extensions

### PR DESCRIPTION
**Pull request by zirain**
xref: https://github.com/envoyproxy/envoy/pull/26266
issues: https://github.com/istio/istio/issues/46277

### CODE REVIEW

**Comment by hanxiaop** [comment]
@zirain I think this also needs to be cherry-picked to release 1.19 branch?

**Comment by zirain** [comment]
> @zirain I think this also needs to be cherry-picked to release 1.19 branch?

If the branch cut is completed, then it is required

**Comment by hanxiaop** [comment]
> > @zirain I think this also needs to be cherry-picked to release 1.19 branch?
> 
> If the branch cut is completed, then it is required

Not sure. I saw the branch was created and the label as well. The branch cut process has not been finished yet.

**Review by lei-tang — APPROVED** [review]

**Pull request merged**
