### PR TITLE
fix(edges reporting): fix error in reporting logic

### PR DESCRIPTION
**Pull request by douglas-reid**
**What this PR does / why we need it**:

Fixes the faulty reporting logic (initialize nanos field) and adds an integration test.

### CODE REVIEW

**Comment by bianpengyuan** [comment]
I removed endpoints from the config and use bootstrap to pass in endpoint in test:
https://github.com/istio/proxy/blob/de7a821bcb3f22e8628c994c8ea09fb25d807cb3/test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go#L100-L101

Context graph endpoint could be passed in similarly:
https://github.com/istio/proxy/blob/de7a821bcb3f22e8628c994c8ea09fb25d807cb3/extensions/stackdriver/common/constants.h#L75

**Comment by bianpengyuan** [comment]
Looks like a real test failure.

**Comment by douglas-reid** [comment]
@bianpengyuan yeah, it looks like #2494 added a mesh id. should be fixed now.

**Pull request merged**
