### PR TITLE
[release-1.5] STS integration test

### PR DESCRIPTION
**Pull request by kyessenov**
Manual cherry-pick of #2700

### CODE REVIEW

**Comment by kyessenov** [comment]
Racing with https://github.com/istio/proxy/pull/2689, which this one also includes.

**Comment by bianpengyuan** [comment]
This blocks https://github.com/istio/proxy/pull/2703

**Comment by fpesce** [comment]
@kyessenov This PR is not merging right now. Would you mind rebasing?

**Comment by kyessenov** [comment]
Rebased and recompiled.

**Comment by kyessenov** [comment]
Gentle nudge @fpesce

**Pull request merged**
