### PR TITLE
using request path when it is grpc request

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by duderino** [comment]
@bianpengyuan @mandarjog it would be good to confirm this path has been normalized before using it

**Comment by bianpengyuan** [comment]
@duderino Thanks for reminding! Yes, this is going to be controlled by config. User could control whether to use traffic data as stats label.

**Comment by kyessenov** [comment]
@duderino the path is coming straight from header_map in Envoy sans the query string. So it is whatever envoy is feeding us which I assume is not normalized. gRPC has to be able to parse it though, and it's not clear whether gRPC accepts dots and double slashes.

**Comment by bianpengyuan** [comment]
Oh, by normalization it means path normalization.. This is for stats only, do we need to do normalization? Isn't it just an opaque string for the system?

**Comment by kyessenov** [comment]
There is no risk of authz violation here. The only risk is cardinality explosion, but we already discussed that.

**Comment by duderino** [comment]
how do you mitigate cardinality explosion?  I recall a prior incident where unbounded strings brought down a user's prometheus cluster.   They considered that a severe Istio bug.

**Comment by bianpengyuan** [comment]
We are making it configurable, so that user could disable using unbounded string like this if they don't trust the source peer.

**Comment by duderino** [comment]
Nice job guys

**Pull request merged**
