### PR TITLE
[release-1.15] 2023 04 04 release 115 (#71)

### PR DESCRIPTION
**Pull request by GregHanson**
* Update envoy sha for security release for release-1.15

* fix ENVOY_SHA

* Fix build compilation

* Fix testdata

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by dhawton — APPROVED** [review]

**Comment by GregHanson** [comment]
leaving `do-not-merge` label pending follow-up discussion

**Comment by jacob-delgado** [comment]
You only need to merge the testdata files

**Comment by jacob-delgado** [comment]
Envoy updated v1.23: https://github.com/envoyproxy/envoy/commits/release/v1.23

**Comment by jacob-delgado** [comment]
Replaced in lieu of https://github.com/istio/proxy/pull/4565

**Comment by jacob-delgado** [comment]
We can keep the branch around for the sha that is built

**Pull request closed without merging**
