### PR TITLE
[release-1.8] Update go control plane 18

### PR DESCRIPTION
**Pull request by jacob-delgado**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
Do we still need this? 1.8.6 is the last release.

**Comment by lambdai** [comment]
@bianpengyuan  We are maintaining the proxy buildable and ready to patch vulnerability required fix.

It's probably not required in the most recent fix but it is nice to sync per https://github.com/istio/proxy/pull/3349

**Comment by bianpengyuan** [comment]
Ok, fwiw the go control plane in this repo is only for integration testing, it does not affect the build at all. Not sure if the test failure is easy to fix or not, if not I guess we can just skip updating go-control-plane here.

**Pull request closed without merging**
