### PR TITLE
update_envoy to get latest commit from WORKSPACE REPO/ORG (#3194)

### PR DESCRIPTION
**Pull request by PiotrSikora**
Backport of #3194, since `release-1.9` branch is broken.

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]

**Comment by ericvn** [comment]
Let me look into what the problem seems to be.

**Comment by ericvn** [comment]
It does appear to be the issue with the extra field.

```
+ sed -i 's/ENVOY_SHA256 = .*/ENVOY_SHA256 = "d126e4600a2eccbd7393e9c315c37462b4035ce4b3802e4223c9364429e395d1  80e9d65a61d6b2ad065e15073db187333910fab5.tar.gz"
```

**Comment by ericvn** [comment]
@googlebot I consent.

**Pull request merged**
