### PR TITLE
Consider 2xx and 3xx status codes as success when deciding to log or not

### PR DESCRIPTION
**Pull request by cagataygurturk**
**What this PR does / why we need it**:

The current implementation considers only 200 as successful result, which is not the reality in practice. This change considers all 4xx and 5xx status codes as failures.

### CODE REVIEW

**Comment by douglas-reid** [comment]
/ok-to-test

Can we add a test that validates the behavior we expect?

**Comment by cagataygurturk** [comment]
> /ok-to-test
> 
> Can we add a test that validates the behavior we expect?

Unfortunately the whole extension lacks test and I am afraid I do not have enough C++ knowledge to construct a new test from scratch. Maybe @gargnupur can chime-in here as the author of the extension.

**Comment by gargnupur** [comment]
LGTM too!! Thanks for the change.

Extension has e2e tests here: https://github.com/istio/proxy/blob/master/test/envoye2e/stackdriver_plugin/stackdriver_test.go#L415:6
You can add a testcase there for say `307 Temporary Redirect` there...

**Comment by cagataygurturk** [comment]
> Extension has e2e tests here: https://github.com/istio/proxy/blob/master/test/envoye2e/stackdriver_plugin/stackdriver_test.go#L415:6
> You can add a testcase there for say `307 Temporary Redirect` there...

Thanks @gargnupur for pointing tests out. I have expanded the cases with more status codes.

**Comment by cagataygurturk** [comment]
Could someone help me to understand whether these test fails are interminent or my code is failing the tests? 

```
--- FAIL: TestStackdriverTCPMetadataExchange (59.21s)
    --- FAIL: TestStackdriverTCPMetadataExchange/BaseCase (9.17s)
        stackdriver_test.go:589: listen tcp :20005: bind: address already in use
```

I feel it is related to test environment but I am also not very familiar with the test infrastructure.

**Comment by gargnupur** [comment]
> Could someone help me to understand whether these test fails are interminent or my code is failing the tests?
> 
> ```
> --- FAIL: TestStackdriverTCPMetadataExchange (59.21s)
>     --- FAIL: TestStackdriverTCPMetadataExchange/BaseCase (9.17s)
>         stackdriver_test.go:589: listen tcp :20005: bind: address already in use
> ```
> 
> I feel it is related to test environment but I am also not very familiar with the test infrastructure.

looks related to test environment..

**Comment by cagataygurturk** [comment]
> > Could someone help me to understand whether these test fails are interminent or my code is failing the tests?
> > ```
> > --- FAIL: TestStackdriverTCPMetadataExchange (59.21s)
> >     --- FAIL: TestStackdriverTCPMetadataExchange/BaseCase (9.17s)
> >         stackdriver_test.go:589: listen tcp :20005: bind: address already in use
> > ```
> > 
> > 
> > I feel it is related to test environment but I am also not very familiar with the test infrastructure.
> 
> looks related to test environment..

@gargnupur Do the extra tests I created in a89851ece6379f7dd7eee433c0b46b11db6afd65 look correct? They failed multiple times, then I reverted them and tests passed. Since I did not know if it is about test infra or tests itself, I am puzzled. If my new tests look correct, I will add them to PR back and fingers crossed.

**Comment by gargnupur** [comment]
> > > Could someone help me to understand whether these test fails are interminent or my code is failing the tests?
> > > ```
> > > --- FAIL: TestStackdriverTCPMetadataExchange (59.21s)
> > >     --- FAIL: TestStackdriverTCPMetadataExchange/BaseCase (9.17s)
> > >         stackdriver_test.go:589: listen tcp :20005: bind: address already in use
> > > ```
> > > 
> > > 
> > > I feel it is related to test environment but I am also not very familiar with the test infrastructure.
> > 
> > 
> > looks related to test environment..
> 
> @gargnupur Do the extra tests I created and deleted in [a89851e](https://github.com/istio/proxy/commit/a89851ece6379f7dd7eee433c0b46b11db6afd65) look correct? They failed multiple times, then I reverted them and tests passed. Since I did not know if it is about test infra or tests itself, I am puzzled. If my new tests look correct, I will add them to PR back and fingers crossed.

@cagataygurturk : They do look correct, but if tests are failing at times they reveal a problem in code itself when running in parallel. You can run these tests locally on your machine too do debug the issue... also, I can help in the afternoon to help debug the tests..

**Comment by cagataygurturk** [comment]
@gargnupur oh now tests passed after changing status codes in existing tests. Are you fine with the current state of tests?

**Comment by lambdai** [comment]
Is redirect correctly handled?

I cannot recall the full context, my impression is that proxy could automatically follow redirect on 3XX. 
It's not a networking topic so I give this PR a +1

**Comment by lambdai** [comment]
@gargnupur @kyessenov I add  do-not-merge label, please remove it once you approve on behalf of telemetry WG

**Pull request merged**
