### PR TITLE
Update Envoy SHA to 436946bb9d (2021-06-04).

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by lambdai** [comment]
dup of https://github.com/istio/proxy/pull/3378/ ?

Or the plan is to address dedicated breakage ?

**Comment by PiotrSikora** [comment]
> dup of #3378 ?
> 
> Or the plan is to address dedicated breakage ?

Oops, I've started working on this yesterday, and I didn't notice #3378 before opening this PR. Thanks for the heads up!

It's not exactly a duplicate, since my plan was to split the update into mutliple PRs, since there is a lot of breaking changes:
- update from 2021-05-18 to 2021-06-04 and fix 2 easy breaking changes (V8 update and include paths),
- solve `absl` vs `std` types mismatch - this is a messy change, and I didn't want to mix it with all the trivial fixes, since it definitely requires a proper review,
- update from 2021-06-04 to 2021-06-15 and fix 2 easy breaking changes (protobuf dependency and well_know_names removal).

The abseil issue might be non-trivial, because of use of `absl` in Envoy and `std` in Proxy-Wasm, which messes up with the Null Plugins, so I think it might sense to roll forward until 2021-06-04 before solving this issue.

cc @bianpengyuan @kyessenov

**Comment by bianpengyuan** [comment]
> > dup of #3378 ?
> > Or the plan is to address dedicated breakage ?
> 
> Oops, I've started working on this yesterday, and I didn't notice #3378 before opening this PR. Thanks for the heads up!
> 
> It's not exactly a duplicate, since my plan was to split the update into mutliple PRs, since there is a lot of breaking changes:
> 
> * update from 2021-05-18 to 2021-06-04 and fix 2 easy breaking changes (V8 update and include paths),
> * solve `absl` vs `std` types mismatch - this is a messy change, and I didn't want to mix it with all the trivial fixes, since it definitely requires a proper review,
> * update from 2021-06-04 to 2021-06-15 and fix 2 easy breaking changes (protobuf dependency and well_know_names removal).
> 
> The abseil issue might be non-trivial, because of use of `absl` in Envoy and `std` in Proxy-Wasm, which messes up with the Null Plugins, so I think it might sense to roll forward until 2021-06-04 before solving this issue.
> 
> cc @bianpengyuan @kyessenov

@PiotrSikora Yeah looks like quite a lot. I struggled a bit now on absl vs std string_view and luckily I've not yet put many efforts on fixing it. So feel free to take over, I will close mine :).

**Review by bianpengyuan — APPROVED** [review]

**Comment by PiotrSikora** [comment]
> @PiotrSikora Yeah looks like quite a lot. I struggled a bit now on absl vs std string_view and luckily I've not yet put many efforts on fixing it. So feel free to take over, I will close mine :).

@bianpengyuan I have fixes for the first 2 breaking changes (include paths in this PR and CentOS build in https://github.com/istio/tools/pull/1578 and https://github.com/istio/test-infra/pull/3387), so that we can roll forward to 2021-06-04... but that's all I have. I don't have a fix for `absl` vs `std`, and I'm unlikely to have more time this week to look into it, so I probably shouldn't be taking over the whole thing.

**Comment by bianpengyuan** [comment]
> @bianpengyuan I have fixes for the first 2 breaking changes (include paths in this PR and CentOS build in istio/tools#1578 and istio/test-infra#3387), so that we can roll forward to 2021-06-04... but that's all I have. I don't have a fix for absl vs std, and I'm unlikely to have more time this week to look into it, so I probably shouldn't be taking over the whole thing.

Ok that's fine. Let's get this in I will take a stab to fix the other breaking changes.

**Pull request merged**
