### PR TITLE
add port to discovery address

### PR DESCRIPTION
**Pull request by rkpagadala**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rkpagadala** [comment]
Recreated the PR since the old one got closed accidentally and I can't reopen.

**Comment by rkpagadala** [comment]
@ldemailly no difference at all. The old one got closed accidentally, So I had to create this one.

**Comment by ldemailly** [comment]
will this auto merge or you want me to merge it or you can do it yourself?

**Pull request merged**
