### PR TITLE
[release-1.10] Update Envoy version - Manual CP of #3284

### PR DESCRIPTION
**Pull request by ericvn**
**What this PR does / why we need it**:

Pull in a version of Envoy that has https://github.com/envoyproxy/envoy/pull/15585.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Hopefully this will fix an istio.io test regression: https://github.com/istio/istio/issues/31616

**Special notes for your reviewer**:

As noted, this is a CP of the Envoy change going into the `master` branch.

### CODE REVIEW

**Comment by Monkeyanator** [comment]
Related: [https://github.com/istio/istio/pull/32144#issuecomment-819223517](https://github.com/istio/istio/pull/32144#issuecomment-819223517)

**Review by lambdai — APPROVED** [review]
LGTM

**Review by Monkeyanator — APPROVED** [review]

**Pull request merged**
