### PR TITLE
Update Envoy SHA to latest with protobuf.Any configs.

### PR DESCRIPTION
**Pull request by PiotrSikora**
For istio/istio#10993.

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Ping.

**Comment by JimmyCYJ** [comment]
@PiotrSikora Is this going into master branch or release-1.1 branch?

**Comment by JimmyCYJ** [comment]
> Is this going into master branch or release-1.1 branch?

Just saw the other PR https://github.com/istio/proxy/pull/2082. Please ignore my question.

**Comment by lizan** [comment]
/lgtm

Thanks!

**Pull request merged**
