### PR TITLE
Make proxy reference envoy-wasm

### PR DESCRIPTION
**Pull request by bianpengyuan**
Try out building istio-proxy with envoyproxy/envoy-wasm repo in extension branch.

### CODE REVIEW

**Comment by kyessenov** [comment]
Should we just use master? It's painful to set-up test infra for each branch.

**Comment by bianpengyuan** [comment]
@kyessenov This is the master of envoy/envoy-wasm repo. Are you referring other repo?

**Comment by kyessenov** [comment]
@bianpengyuan I was referring to the target branch. It looks like you want to merge into istio:extension. This is a new branch that has no test-infra set-up, which mean I have a green merge button available to me without test checks.

**Comment by bianpengyuan** [comment]
@kyessenov I do see circle test running for the branch, though it is not blocking the change. The only concern is envoy-wasm might not be as stable (I don't think there are tech infra setup at all in that repo). But considering the code change made there are all in filters scope, so maybe it is fine. cc @mandarjog

**Comment by bianpengyuan** [comment]
We need to test out how long the build is going run on prow. Since right now we are building from envoy-wasm which builds a v8 engine and is very slow, we might not want to make master slow for changes not related to new extensions.

There is already a wasm branch, we should just use that one that it has already had test-infra set up.

**Pull request closed without merging**
