### PR TITLE
Bump enoy version to pickup json access log fix

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

**What this PR does / why we need it**:
Bump envoy version to pickup json access log fix envoyproxy/envoy#5024

```release-note
fix json access logging
```

### CODE REVIEW

**Comment by cmluciano** [comment]
cc @GregHanson

**Comment by linsun** [comment]
I believe @vadimeisenbergibm updated this 8 days ago -- https://github.com/istio/proxy/pull/2041

**Comment by cmluciano** [comment]
Yes that was for the master branch but not 1.1 . I picked the commit we needed exactly but did not know how far to go. Maybe we can just cherry pick his commit to this release branch?

**Comment by linsun** [comment]
@vadimeisenbergibm 's PR is for master, and this is for 1.1... Do you also need to update the WORKPLACE file?

**Pull request merged**
