### PR TITLE
add route flags to disable check and report independently.

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by rshriram** [comment]
Oh shoot. I did the same stuff in another pr. Sorry for the duplication

**Comment by rshriram** [comment]
@qiwzhang this is nice.. Can you also add the ability to disable check alone from tcp filter as well ?
I think that would require a global config at mixer filter level.

**Comment by qiwzhang** [comment]
@rshriram OK,  I will use a separate PR for tcp

**Comment by rshriram** [comment]
@qiwzhang I am repurposing my PR to disable only TCP check. And we can use this for HTTP check disabling..

**Comment by rshriram** [comment]
partly fixes #448

**Pull request merged**
