### PR TITLE
wasm: remove unused Istio specific Wasm code under src.

### PR DESCRIPTION
**Pull request by mathetake**
Combined with #3404, this PR removes unused Istio specific Wasm extension code under src. Necessary change per https://github.com/envoyproxy/envoy/pull/17268.

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Comment by mathetake** [comment]
OK I found that the IstioExtension class calls `registerPrometheusNamespace("istio");` in its constructor so we have to do it somewhere. This is related to https://github.com/envoyproxy/envoy/issues/14920 https://github.com/istio/istio/issues/27635 and maybe we should support that via foregin functions.

**Comment by mathetake** [comment]
so for now, leave the namespace registration as-is, will come back to this after I fixed  https://github.com/envoyproxy/envoy/issues/14920

**Comment by mathetake** [comment]
fyi: created a patch https://github.com/envoyproxy/envoy/pull/17357 to allow plugins to register namespaces

**Pull request merged**
