### PR TITLE
add x-goog-user-project header to stackdriver call out

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:
This adds `x-goog-user-project` header to metrics, log and context graph call out.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mandarjog** [comment]
Is this a cherry pick up into master?

**Comment by bianpengyuan** [comment]
Part of it (metric) is a cherry-pick from https://github.com/istio/proxy/pull/2703. For log and edge, we used `onCreateInitialMetadata` callback in release-1.{4,5} to inject header, but we could actually just use `initial_metadata` to do it: https://github.com/envoyproxy/envoy/blob/9186ebf374b1bd7d7c65ed1cec748377f88ec0a7/api/envoy/api/v2/core/grpc_service.proto#L225  https://github.com/envoyproxy/envoy-wasm/pull/461 removes the onCreateInitialMetadata from the ABI.

**Comment by kyessenov** [comment]
Do you want to add a test to the integration test to validate the presence of the header?

**Comment by bianpengyuan** [comment]
The test is already there: https://github.com/istio/proxy/pull/2731/files#diff-9a64bdacaaf291cc03cca6cf3c038174R220

**Comment by kyessenov** [comment]
Yes, I'm confused how the tests passed before without this change. How did it work before?

**Comment by bianpengyuan** [comment]
If you look at the newly added linked line (line 220), it searches for and verifies header value. Without .cc change in this PR, SD test will fail.

**Comment by kyessenov** [comment]
Oh, OK. Sorry about the silly question, I think I lost some context how to navigate this code base...

**Pull request merged**
