### PR TITLE
remove stackdriver

### PR DESCRIPTION
**Pull request by kyessenov**
Change-Id: I3b91f2b05b7e0fe6f4878311741cc74162f84934

Issue: https://github.com/istio/istio/issues/50808

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by kyessenov** [comment]
`FATAL: ThreadSanitizer: unexpected memory mapping 0x5c9bd4d2b000-0x5c9bd4d4b000`

@howardjohn Did we upgrade the CI hardware or kernel version?

**Comment by howardjohn** [comment]
> `FATAL: ThreadSanitizer: unexpected memory mapping 0x5c9bd4d2b000-0x5c9bd4d4b000`
> 
> @howardjohn Did we upgrade the CI hardware or kernel version?

CI nodes were bumped from GKE 1.29.x to 1.29.y today. I doubt that would cause issues...?

Dockerfile was changed recently, about 1 week ago. We bumped the main image to `ubuntu:noble`. The proxy image did not change, but it does copy some stuff from the main one which could have caused changes?

Looks like this broke first in https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_proxy/5548/test-tsan_proxy/1790733976940318720 at 6am this morning? The dockerfile change was before that, and the CI node upgrade was after

**Comment by howardjohn** [comment]
nvm, first was https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_proxy/5550/test-tsan_proxy/1790778516095111168 at 9:17am. Nodes upgraded around then

**Comment by kyessenov** [comment]
Kernel version matters for TSan since it seems to be coupled with clang version. We'll have to turn off TSan or downgrade kernel?

**Review by lei-tang — APPROVED** [review]

**Pull request merged**
