### PR TITLE
Update Envoy and change dynamo filter to contrib

### PR DESCRIPTION
**Pull request by ericvn**
**What this PR does / why we need it**:

The current automation fails to pass as the dynamo filter moved to contrib

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

See https://github.com/istio/proxy/pull/3892

**Special notes for your reviewer**:

### CODE REVIEW

**Review by GregHanson — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
test test_proxy

**Pull request merged**
