### PR TITLE
update envoy sha for sni

### PR DESCRIPTION
**Pull request by ijsnellf**
**What this PR does / why we need it**:
Updates Envoy SHA so that SNI is available. SNI support was merged here: envoyproxy/envoy#3217

I am not sure about the update process for istio/proxy, so please double check this PR.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by lizan** [comment]
It looks like it is due to the change to method signature of `sendLocalReply`, so the code change should be easy. Though if you're not familiar with the code base, someone from proxy can handle it.

**Comment by ijsnellf** [comment]
I can give it a try, but it would probably make more sense for someone with familiarity with the code base to make the changes.

**Comment by rlenglet** [comment]
#1758 did those changes but was closed before merging.

**Comment by qiwzhang** [comment]
Replace it with https://github.com/istio/proxy/pull/1759

**Pull request closed without merging**
