### PR TITLE
[release-1.19] Automated branching step 4

### PR DESCRIPTION
**Pull request by ericvn**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ksubrmnn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
The envoy update in the main branch just finished so hopefully the tests won't collide with those in another branch.

**Pull request merged**
