### PR TITLE
Added /producer/by_consumer metrics.

### PR DESCRIPTION
**Pull request by mangchiandjjoe**

### CODE REVIEW

**Comment by mandarjog** [comment]
@louiscryan  @qiwzhang Does `contrib/endpoints` code need to be in the proxy repo? 
Looks like it could be a separate repo which can depend on proxy.

**Comment by qiwzhang** [comment]
current plan is: @lizan will move grpc transcoding code to a separate grpc repo so Istio/proxy (envoy) can use it.  After that,  we will move api_manager code (for ESP) back to the private ESP repo.

**Comment by kyessenov** [comment]
Before we start moving large amount of code around again, can we decide if we ever need API management features in the proxy. I understand that the two core piece apart from transcoding are monitoring/logging per method and authentication/authorization. Are we confident we can do both purely on the mixer side?

**Comment by qiwzhang** [comment]
@kyessenov you are right,  beside grpc transcoding,  there are auth, and calling Chemist directly.  we need to answer:  where will jwt auth checking be for istio/proxy?   will istio/proxy ever call Chemist directly?

**Pull request merged**
