### PR TITLE
Release-0.8: Update envoy sha to bb6762a058

### PR DESCRIPTION
**Pull request by qiwzhang**
**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by qiwzhang** [comment]
Some Jwt_authn integration tests failed with latest Envoy code.  They are using old Envoy integration test framework.  I am trying to switch them to use the new framework.

**Comment by PiotrSikora** [comment]
@qiwzhang since this isn't merged yet, could you update to https://github.com/envoyproxy/envoy/commit/12c470e666d23f1cedaea92cdae6c747d6081dfe? It's one commit ahead of this PR and contains something useful for Istio. Thanks!

**Comment by qiwzhang** [comment]
@PiotrSikora OK.

**Pull request merged**
