### PR TITLE
Update proxy to envoy-wasm@9cf22b8 (12/19)

### PR DESCRIPTION
**Pull request by diemtvu**
Sync to latest https://github.com/envoyproxy/envoy-wasm/commit/9cf22b8
This includes changes for `allow_missing` JWT (https://github.com/envoyproxy/envoy/issues/8909).

Issue: https://github.com/istio/istio/issues/18399

### CODE REVIEW

**Comment by yxue** [comment]
You can merge this change https://github.com/istio/proxy/pull/2608/files after it's merged.

**Comment by diemtvu** [comment]
> You can merge this change #2608 after it's merged. The failure should be fixed.

Someone still working on https://github.com/istio/proxy/pull/2608?

**Comment by bianpengyuan** [comment]
https://github.com/istio/proxy/pull/2611 has been merged which supersedes #2608

**Comment by kyessenov** [comment]
Please fix the build. You might also need to change request_protocol to request.protocol if the integration tests fail (not sure if it made it here).

**Pull request merged**
