### PR TITLE
Update envoy sha

### PR DESCRIPTION
**Pull request by rshriram**

### CODE REVIEW

**Comment by kyessenov** [comment]
skylark rule changed. I think @lizan had a working bazel update build.

**Comment by rshriram** [comment]
Its been 3 months since we updated Envoy. So much for the bots

**Comment by mandarjog** [comment]
really? it was that old :-(  
@kyessenov this also means that the proxy crash we see in e2e tests is unrelated to base envoy.

**Comment by qiwzhang** [comment]
@lizan could you submit your PR to update proxy to latest Envoy?

**Comment by rkpagadala** [comment]
@rshriram Envoy has always been updated manually, not sure why. Istio eng prod team has been asked to update envoy using bots only last week. We have it on our list to get done.

**Comment by lizan** [comment]
Envoy's C++ interface is never stable so it isn't always simply updating SHA. Bot can perform SHA only changes, but if the build fails we should get notified.

**Comment by lizan** [comment]
I'll have the updating PR by EoD

**Comment by lizan** [comment]
Closing in favor of #922

**Pull request closed without merging**
