### PR TITLE
update envoy sha

### LINKED ISSUE #614: Latest SHA of istio/proxy crashes in pilot e2e tests when auth is enabled
The latest SHA of istio/proxy crashes in pilot e2e tests when auth is enabled. When the istio/proxy sha is updated from f8b4de9a80f1d6b500b3148e0e3364daffbb9dfc to 212a8e48188b38870717b2704c593ed3ae0d60f2, the istio-pilot istio-proxy container crashes with following logs:
```
W1030 21:00:20.731260 1 agent.go:204] Epoch 0 terminated with an error: signal: aborted (core dumped)
W1030 21:00:20.731292 1 agent.go:303] Aborted all epochs
W1030 21:00:20.731314 1 watcher.go:299] Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory
I1030 21:00:20.731323 1 agent.go:229] Epoch 0: set retry delay to 25.6s, budget to 2
I1030 21:00:46.331763 1 agent.go:261] Reconciling configuration (budget 2)
I1030 21:00:46.331901 1 agent.go:281] Epoch 0 starting
I1030 21:00:46.331921 1 watcher.go:269] Envoy command: [-c /etc/istio/proxy/envoy_pilot_auth.json --restart-epoch 0 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster istio-proxy --service-node pilot~~istio-pilot-2221366506-fvgtk.istio-test-q9xrm~istio-test-q9xrm.svc.cluster.local]
[2017-10-30 21:00:46.361][26][warning][main] external/envoy/source/server/server.cc:157] initializing epoch 0 (hot restart version=9.200.16384.127)
[2017-10-30 21:00:46.428][26][critical][assert] external/envoy/source/common/ssl/context_impl.cc:414] assert failure: cn_index >= 0
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:101] Caught Aborted, suspect faulting address 0x1a
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:85] Backtrace obj</lib/x86_64-linux-gnu/libc.so.6> thr<0> (use tools/stack_decode.py):
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #0 0x7f51c6fcc428
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #1 0x7f51c6fce029
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:93] thr<0> obj</usr/local/bin/envoy>
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #2 0x798dc2
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #3 0x79e659
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #4 0x64a6a6
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #5 0x64bb37
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #6 0x87cd7f
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #7 0x63902b
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #8 0x636ec7
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #9 0x537c81
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #10 0x535c77
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:93] thr<0> obj</lib/x86_64-linux-gnu/libc.so.6>
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #11 0x7f51c6fb782f
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:93] thr<0> obj</usr/local/bin/envoy>
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:95] thr<0> #12 0x416ae8
[2017-10-30 21:00:46.428][26][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:97] end backtrace thread 0
W1030 21:00:46.435016 1 agent.go:204] Epoch 0 terminated with an error: signal: aborted (core dumped)
W1030 21:00:46.435058 1 agent.go:303] Aborted all epochs
W1030 21:00:46.435106 1 watcher.go:299] Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory
I1030 21:00:46.435113 1 agent.go:229] Epoch 0: set retry delay to 51.2s, budget to 1
```

Decoded:
```
isaiah@nostromo:~$ cat ~/coredump | envoy/tools/stack_decode.py
[2017-10-30 19:24:35.036][10][warning][main] external/envoy/source/server/server.cc:157] initializing epoch 0 (hot restart version=9.200.16384.127)
[2017-10-30 19:24:35.148][10][critical][assert] external/envoy/source/common/ssl/context_impl.cc:414] assert failure: cn_index >= 0
[2017-10-30 19:24:35.148][10][critical][backtrace] bazel-out/local-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:101] Caught Aborted, suspect faulting address 0xa
[2017-10-30 19:24:35.148][10][critical] Backtrace (most recent call first) from thread 0:
  #1 ?? ??:0
  #2 ?? ??:0
  #3 
  #4 Envoy::Ssl::ServerContextImpl::ServerContextImpl(Envoy::Ssl::ContextManagerImpl&, Envoy::Stats::Scope&, Envoy::Ssl::ServerContextConfig&, Envoy::Runtime::Loader&) at context_impl.cc:414 (discriminator 3)
  #5 Envoy::Ssl::ContextManagerImpl::createSslServerContext(Envoy::Stats::Scope&, Envoy::Ssl::ServerContextConfig&) at context_manager_impl.cc:34
  #6 Envoy::Server::ListenerImpl::ListenerImpl(envoy::api::v2::Listener const&, Envoy::Server::ListenerManagerImpl&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long) at listener_manager_impl.cc:99
  #7 Envoy::Server::ListenerManagerImpl::addOrUpdateListener(envoy::api::v2::Listener const&) at listener_manager_impl.cc:197
  #8 Envoy::Server::Configuration::MainImpl::initialize(envoy::api::v2::Bootstrap const&, Envoy::Server::Instance&, Envoy::Upstream::ClusterManagerFactory&) at configuration_impl.cc:48
  #9 Envoy::Server::InstanceImpl::initialize(Envoy::Server::Options&, std::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::Server::ComponentFactory&) at server.cc:237 (discriminator 8)
  #10 Envoy::Server::InstanceImpl::InstanceImpl(Envoy::Server::Options&, std::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::TestHooks&, Envoy::Server::HotRestart&, Envoy::Stats::StoreRoot&, Envoy::Thread::BasicLockable&, Envoy::Server::ComponentFactory&, Envoy::ThreadLocal::Instance&) at server.cc:68 (discriminator 1)
  #11 Envoy::main_common(Envoy::OptionsImpl&) at main_common.cc:85
  #12 main at main.cc:47
  #13 
  #14 ?? ??:0
  #15 
  #16 _start at ??:?
  #17 
```

The issue appears to be the assert here: 
https://github.com/envoyproxy/envoy/blob/master/source/common/ssl/context_impl.cc#L414

```
  int cn_index = X509_NAME_get_index_by_NID(cert_subject, NID_commonName, -1);
  RELEASE_ASSERT(cn_index >= 0);
```

### PR DESCRIPTION
**Pull request by rkpagadala**
fixes #614

### CODE REVIEW

**Comment by ldemailly** [comment]
thanks! any idea why
```
ERROR: /home/jenkins/workspace/proxy/presubmit/WORKSPACE:71:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'io_bazel_rules_go').
ERROR: Error evaluating WORKSPACE file.
ERROR: error loading package '': Encountered error while reading extension file 'test/repositories.bzl': no such package '@com_github_istio_mixer//test': error loading package 'external': Could not load //external package.
ERROR: Skipping '//...': no targets found beneath ''.
```

**Comment by lizan** [comment]
Can you add `skip_targets = ["io_bazel_rules_go"]` to `envoy_dependencies` calls in L50, that should fix presubmit

**Comment by lizan** [comment]
@qiwzhang Is the pilot-regression test is expected? Seems the error log is related to added attributes in config: https://testing.istio.io/job/proxy/job/pilot-regression/746/execution/node/92/log/. If so feel free to merge this.

@rkpagadala `/retest` doesn't work in proxy :)

**Pull request merged**
