### PR TITLE
Fix root cert for opencensus library

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:
Read root cert file, and use the content for opencensus stub. This change references https://github.com/envoyproxy/envoy/blob/1dc6e43b23e7de27064fa4e30c39a637697287a9/source/common/filesystem/posix/filesystem_impl.cc#L93.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@kyessenov  We probably should skip those stress test when testing with tsan? It is too flaky to actually bring any value now.

**Comment by kyessenov** [comment]
SGTM. Feel free to disable it and file an issue to re-enable it back later.

**Pull request merged**
