### PR TITLE
add bazel build args into test framework and do not fail silently

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by SecurityInsanity** [comment]
This will be fixed by: https://github.com/istio/proxy/pull/3029 (included this patch as a result). Think we can close this, can you confirm @bianpengyuan ?

**Comment by bianpengyuan** [comment]
Ah yes, nvm. Closing.

**Pull request closed without merging**
