### PR TITLE
build: update clang and clang-format to version 8.0.0.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Could someone with access to DockerHub build the CI image? Thanks! cc @bianpengyuan

**Comment by bianpengyuan** [comment]
@PiotrSikora I got an error when building the image, are you able to build it?

```
E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-backports_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)
```

**Comment by PiotrSikora** [comment]
@bianpengyuan I was getting this error as well, but it's unrelated to changes in this PR. Seems to be something flaky with `debian.org`. If you try a few times, it will eventually build.

**Comment by bianpengyuan** [comment]
@PiotrSikora Pushed.

**Comment by bianpengyuan** [comment]
@PiotrSikora Looks like bazel stuck problem is not fully resolved? and I think you need to explicitly list the tests in order to re-trigger them.

/test proxy-presubmit-tsan
/test proxy-presubmit-asan

**Comment by PiotrSikora** [comment]
> @PiotrSikora Looks like bazel stuck problem is not fully resolved?

Indeed... @utka @icygalz is there any way we could improve error reporting in Prow? Even if Bazel is crashing, we should be able to notice that and either fail or rerun tests, instead of hanging forever.

> and I think you need to explicitly list the tests in order to re-trigger them.

Not according to @istio-testing bot:

> @PiotrSikora: The following tests failed, say /retest to rerun them all:

Though, it indeed looks that it didn't rerun them until your comment. Weird.

**Comment by bianpengyuan** [comment]
@PiotrSikora I think `retest` was meant for failed test but not hanging tests.

**Pull request merged**
