### PR TITLE
merge 1.0 branch to master

### PR DESCRIPTION
**Pull request by rkpagadala**
**What this PR does / why we need it**:
merge 1.0 branch to master

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kyessenov** [comment]
Can we please get https://github.com/istio/proxy/pull/1884?
We need admins to merge. @rshriram ? @geeknoid ?

**Comment by rkpagadala** [comment]
@kyessenov will wait for 1884
/hold

**Comment by rkpagadala** [comment]
@PiotrSikora do you know why the circleci is failing

**Comment by PiotrSikora** [comment]
@rkpagadala old Bazel (and missing ninja), you need to copy lines added to `build` target to `linux_asan` and `linux_tsan` as well.

**Pull request merged**
