### PR TITLE
Update Envoy-WASM SHA to latest with C++14 fix.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
Builds fine locally. As a follow up we should investigate why CI passed the first time.

**Comment by PiotrSikora** [comment]
> Builds fine locally. As a follow up we should investigate why CI passed the first time.

That's because `libc++` allows `std::string_view` in C++14, and we use `libc++`.

```
$ cat main.cc
```
```
#include <string>

int main() {
   std::string_view x;
   return 1;
}
```
```
$ clang++ -std=c++14 main.cc
```
```
main.cc:4:9: error: no type named 'string_view' in namespace 'std'
   std::string_view bla;
   ~~~~~^
1 error generated.
```
```
$ clang++ -std=c++14 -stdlib=libc++ main.cc
```
```
(OK)
```

**Comment by kyessenov** [comment]
@PiotrSikora IMHO libc++ is not conformant to C++ spec, and we should not side on its peculiar behavior.

**Comment by PiotrSikora** [comment]
> @PiotrSikora IMHO libc++ is not conformant to C++ spec, and we should not side on its peculiar behavior.

I'm not saying that we should, I'm just saying why the CI passed.

**Comment by kyessenov** [comment]
OK. Should we build without libc++ in CI then? That will keep us honest to c++ standards.

**Comment by PiotrSikora** [comment]
> OK. Should we build without libc++ in CI then? That will keep us honest to c++ standards.

We're shipping production binaries with `libc++` and that's unlikely to change.

If you want to add another CI target testing C++ conformance using `stdlibc++`, be my guest.

**Comment by PiotrSikora** [comment]
@howardjohn I've been seeing some build timeouts recently. Could you check if we're swapping on the build machines?

**Pull request merged**
