### PR TITLE
t-test prototype

### PR DESCRIPTION
**Pull request by lizan**
Passes with #27

### CODE REVIEW

**Comment by qiwzhang** [comment]
Could you describe how it is done?   I saw the binary is using envoy-esp,  but Nginx is loaded, and every where name is using Nginx.   and nginx config is used inside t test.    If Nginx is used,  but we don't have ESP module code for Nginx here

**Comment by lizan** [comment]
I tried to make the t-test can share most part with our nginx test as well, so I didn't delete the nginx specific part from `check.t`.

Instead of `$t->run`, it use `$t->run_daemon` to start an envoy-esp, config file generated in `ApiManager.pm`.

In BUILD file nginx actually pointed to envoy-esp.

**Comment by kyessenov** [comment]
This is confusing. Can you replace all "nginx" occurrences with envoy?
What's the migration plan for the t-test code? Are we moving it to this repo?

**Comment by lizan** [comment]
@kyessenov This is just a prototype to review.
I will update with correct words (probably "proxy" instead of envoy or nginx).

Let's discuss migration plan later.

**Comment by qiwzhang** [comment]
I see.  This is good, a big step in the right direction.  A couple suggestions
1) for easy code review, could you use a separate PR to just copy the existing codes.  Then this PR just show the diff?
2) may be we can create an abstract layer to handle Nginx/Envoy stuff, such as config and running.

such as:

$t = proxy_test;
$t->set_config(
"listen_port": xxx
"service_config_file": xxx
)
$t->run()

Ideally,  at bazel proxy.bzl level, we have flag to switch proxy for Nginx or Envoy.

**Comment by mandarjog** [comment]
Are `t tests` still the preferred framework? 
I thought we were moving to a go based testing fw. @lizan ?

**Pull request closed without merging**
