### PR TITLE
Test build-tools image

### PR DESCRIPTION
**Pull request by ericvn**
**What this PR does / why we need it**:

Test the new build-tools image to see if there are any more required changes

### CODE REVIEW

**Comment by ericvn** [comment]
```
Downloading clang-format: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-aarch64-linux-gnu
Installing required clang-format 12.0.1 to /home/clang-12.0.1
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Could not install required clang-format. Skip formatting.
```

**Comment by ericvn** [comment]
also:
```
==================== Test output for //extensions/common:util_test:
/home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/11025/execroot/io_istio_proxy/bazel-out/k8-fastbuild/bin/extensions/common/util_test.runfiles/io_istio_proxy/extensions/common/util_test: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

**Comment by ericvn** [comment]
release-test failure:
```
+ UBUNTU_RELEASE=bionic
+ [[ bionic == \x\e\n\i\a\l ]]
+ echo 'Must run on Ubuntu 16.04 (Xenial).'
Must run on Ubuntu 16.04 (Xenial).
+ exit 1
```

**Comment by ericvn** [comment]
At this point, I'm not sure that my path is the correct one. Just trying to fix errors caused by updating the tooling versions.

**Comment by kyessenov** [comment]
@ericvn 
I have the fixes in #4922 , but I need the latest CI image for it to pass. I see it's still using the old image:

```
  job: test-arm-arm64_proxy
  namespace: test-pods
  pod_spec:
    automountServiceAccountToken: false
    containers:
    - command:
      - ./prow/proxy-presubmit.sh
      env:
      - name: ARCH_SUFFIX
        value: arm64
      - name: BUILD_WITH_CONTAINER
        value: "0"
      image: gcr.io/istio-testing/build-tools-proxy:master-1910456f932b25c53af846d99330f74d6569edb8
```

**Comment by ericvn** [comment]
```
[31m[1mERROR: [0m/home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/com_github_google_flatbuffers/src/BUILD.bazel:9:11: Compiling src/reflection.cpp [for tool] failed: (Exit 127): clang-14 failed: error executing command (from target @com_github_google_flatbuffers//src:flatbuffers) 
  (cd /home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/5/execroot/io_istio_proxy && \
  exec env - \
    CC=/usr/lib/llvm/bin/clang \
    CXX=/usr/lib/llvm/bin/clang++ \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
  /usr/lib/llvm/bin/clang-14 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-stdlib=libc++' -MD -MF bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/com_github_google_flatbuffers/src/_objs/flatbuffers/reflection.d '-frandom-seed=bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/com_github_google_flatbuffers/src/_objs/flatbuffers/reflection.o' '-DBAZEL_CURRENT_REPOSITORY="com_github_google_flatbuffers"' -iquote external/com_github_google_flatbuffers -iquote bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/com_github_google_flatbuffers -Ibazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/com_github_google_flatbuffers/src/_virtual_includes/flatbuffers -g0 -g0 '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_github_google_flatbuffers/src/reflection.cpp -o bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/com_github_google_flatbuffers/src/_objs/flatbuffers/reflection.o)
# Configuration: c096c80a30df5b7879452e72bbb7cff80497073d21c914f0f28534e427522967
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/usr/lib/llvm/bin/clang-14: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
[31m[1mERROR: [0m/home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/external/upb/BUILD:531:11: Compiling upb/collections/map.c [for tool] failed: (Exit 127): clang-14 failed: error executing command (from target @upb//:collections_internal) 
  (cd /home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/3/execroot/io_istio_proxy && \
  exec env - \
    CC=/usr/lib/llvm/bin/clang \
    CXX=/usr/lib/llvm/bin/clang++ \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
  /usr/lib/llvm/bin/clang-14 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/upb/_objs/collections_internal/map.d '-frandom-seed=bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/upb/_objs/collections_internal/map.o' '-DBAZEL_CURRENT_REPOSITORY="upb"' -iquote external/upb -iquote bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/upb -g0 '-std=c99' -Wall -Wstrict-prototypes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/upb/upb/collections/map.c -o bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/upb/_objs/collections_internal/map.o)
# Configuration: c096c80a30df5b7879452e72bbb7cff80497073d21c914f0f28534e427522967
# Execution platform: @local_config_platform//:host
```

**Comment by ericvn** [comment]
Closing based on https://github.com/istio/proxy/pull/4922

**Pull request closed without merging**
