### PR TITLE
fix all shellcheck for files in scripts and extension directory

### PR DESCRIPTION
**Pull request by shalk**
**What this PR does / why we need it**:
fix shellcheck  in scritps and extension, Improving the robustness of scripts 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

the shellcheck  code i fixed as follow:
[SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230): which is non-standard. Use builtin 'command -v' instead.
[SC2003](https://github.com/koalaman/shellcheck/wiki/SC2003): expr is antiquated. Consider rewriting this using $((..)), ${} or [[ ]].
[SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164): Use 'pushd ... || exit' or 'pushd ... || return' in case pushd fails.
[SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086):  Double quote to prevent globbing and word splitting.
[SC2207](https://github.com/koalaman/shellcheck/wiki/SC2207):  Prefer mapfile or read -a to split command output (or quote to avoid splitting).
[SC2145](https://github.com/koalaman/shellcheck/wiki/SC2145): Argument mixes string and array.     Use * or separate argument.
[SC2064](https://github.com/koalaman/shellcheck/wiki/SC2064): Use single quotes, otherwise this expands now rather than when signalled.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by shalk** [comment]
> Could you add script lint check to lint target?

hi, 
I found target `lint-scripts`  in   [Makefile.common.mk  ](https://github.com/istio/proxy/blob/master/common/Makefile.common.mk)
```
lint-scripts:
	@${FINDFILES} -name '*.sh' -print0 | ${XARGS} shellcheck
```
I think `make lint-scripts` can check this . 

But make lint-scripts will fail , because I have not fixed shellcheck  for  bash scripts in directory `prow` and `tools` ( I do not want  to  change too many files first time)


I consider to add this 
```
 LINT_SCRIPTS_DIR ?= . 
lint-scripts-dir:
         @find ${LINT_SCRIPTS_DIR} \( -path ./common-protos -o -path ./.git -o -path ./out -o -path ./.github -o -path ./licenses \) -prune -o     -type f -name '*.sh' -print0 |\
                 ${XARGS} shellcheck
```
so we can check  a directory by follow command.

```
export  LINT_SCRIPTS_DIR="scripts"; make lint-scripts-dir  
export  LINT_SCRIPTS_DIR="extension"; make lint-scripts-dir 
```

Or should i  fix `prow`  and `tools`  in this PR ?

can you give some adive ?

**Comment by bianpengyuan** [comment]
Yes, please fix scripts in the prow and tool all together. thanks!

**Comment by shalk** [comment]
> Yes, please fix scripts in the prow and tool all together. thanks!

I have fixed these scripts !

**Comment by bianpengyuan** [comment]
Could you add `lint-scripts` to here as `lint-go`: https://github.com/istio/proxy/blob/4d68ab70a3d3c720591e746c5932cfb368a9a1c6/Makefile.core.mk#L113 ? this will make ci run script lint.

**Comment by shalk** [comment]
> Could you add `lint-scripts` to here as `lint-go`:
> 
> https://github.com/istio/proxy/blob/4d68ab70a3d3c720591e746c5932cfb368a9a1c6/Makefile.core.mk#L113
> 
> ? this will make ci run script lint.

done

**Pull request merged**
