### PR TITLE
Update dependencies and fix compile errors.

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Signed-off-by: JimmyCYJ <jimmychen.0102@gmail.com>

**What this PR does / why we need it**:
Update Envoy SHA to 8607e912a1df840da1080b7b0d4a9ed6bc247c39 and fix dependencies as well as compile issues.

```release-note
NONE
```

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
Local build passes on my workstation. There are some more errors to fix.

**Comment by JimmyCYJ** [comment]
@PiotrSikora Seems that I need to update bazel version for circleCI. 
I notice that you recently update [.circleci/config.yml](https://github.com/istio/proxy/blob/6215156a475131732a8a7620ee0aa49fd082101f/.circleci/config.yml#L6). Do you know how to build a newer image, e.g. istio/ci:go1.10-bazel0.18-clang6.0 ?

**Comment by PiotrSikora** [comment]
@JimmyCYJ you need to update `Dockerfile` and `Makefile` (see: https://github.com/istio/proxy/commit/c09169a7bb8af5869e5ca5341ee8cdc8bfbe5b64), build new image and push it to DockerHub (but you need to have access to do that, cc @rshriram).

**Comment by JimmyCYJ** [comment]
> @JimmyCYJ you need to update `Dockerfile` and `Makefile` (see: [c09169a](https://github.com/istio/proxy/commit/c09169a7bb8af5869e5ca5341ee8cdc8bfbe5b64)), build new image and push it to DockerHub (but you need to have access to do that, cc @rshriram).

Thanks @PiotrSikora I have created https://github.com/istio/proxy/pull/1994 to update bazel.

**Comment by rshriram** [comment]
You have ot push the build image to docker hub. Otherwise, it won't work

**Pull request merged**
