### PR TITLE
Revert "Make envoy archive configurable from environment."

### PR DESCRIPTION
**Pull request by lizan**
Reverts istio/proxy#2496, meanwhile I prefer revert this. Let me know if you disagree @clarketm @PiotrSikora

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Do you have an alternative solution? We need this capability for private builds.

**Comment by lizan** [comment]
@PiotrSikora this does actually break private builds (pointing to envoy to private repo): https://github.com/istio/proxy/pull/2496#issuecomment-548840106

**Comment by clarketm** [comment]
@lizan based on your comments, I can see auth is implemented directly in [`http_archive`](https://github.com/bazelbuild/bazel/blob/0971420455c0758aa90e17bac0c6d852e0b9afc2/tools/build_defs/repo/http.bzl#L42). I wan't aware this was not configurable for `repository_rule` I was. I can rework an alternate solution.

**Comment by lizan** [comment]
@clarketm yeah if you can rework on an alternative that works for me too. meanwhile I'm inclining to revert.

**Comment by PiotrSikora** [comment]
@lizan can you resolve conflicts?

**Comment by lizan** [comment]
@PiotrSikora done

**Comment by PiotrSikora** [comment]
@googlebot rescan

**Pull request merged**
