### PR TITLE
update xeniel to bionic

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:
Fixes istio/istio#18977
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Fixes https://github.com/istio/istio/issues/18977

**Comment by bianpengyuan** [comment]
Close since binary built with bionic will break VM use case and distroless image.

**Comment by kyessenov** [comment]
@PiotrSikora what are our expectations for the release image? Do we preserve the minimal requirements from Envoy (GCC 7 or Clang/LLVM 7 on Ubuntu 16LTS). The recent moves to clang-9 and libc++ make me think that no longer works.

**Comment by lizan** [comment]
@kyessenov the move of toolchain and standard library doesn't affect where the binary can be run. istio/proxy is already on libc++ since last release.

**Comment by kyessenov** [comment]
I recall that ASAN build requires dynamic linking, so the base does matter.
It's fine if we xenial, but someone needs to make sure all dynamically linked libraries are there.

**Comment by lizan** [comment]
ASAN build is not dynamically linked because it is not intended to ship (run out side or build container). The only dynamic linking library is libc for the release binary.

**Comment by PiotrSikora** [comment]
@kyessenov building on Ubuntu 16.04 is purely about minimizing required glibc version. Otherwise those binaries won't run on CentOS, etc.

@lizan that's not entirely true. ASan is dynamically linked right now (see: https://github.com/envoyproxy/envoy/pull/8555), and we definitely intend to publish ASan Docker images in the foreseeable future.

**Comment by lizan** [comment]
@PiotrSikora let's build another statically linked asan+ubsan image/deb with statically linked libc++, especially for ubsan, there's ubsan-minimal runtime, which is the one for shipping.

**Comment by PiotrSikora** [comment]
@lizan SGTM.

**Pull request closed without merging**
