### PR TITLE
update envoy and workload proto

### PR DESCRIPTION
**Pull request by kyessenov**
Fixes https://github.com/istio/istio/issues/43936
Fixes recent out-of-sync envoy in istio.

### CODE REVIEW

**Comment by ericvn** [comment]
Thanks @kyessenov for doing this. I had just decided to start looking at the changes needed to get things working and when I started to look at making them here, I noticed that they seem to already be made (based changes I saw in https://github.com/envoyproxy/envoy/pull/25981). Figuring out they were made 48 minutes prior I knew someone beat me to it (and probably got them done much quicker than I could).

**Comment by kyessenov** [comment]
@ericvn No problem. Better keep it up to date than accumulate too many changes.

**Pull request merged**
