### PR TITLE
Avoid specifying root cert at Stackdriver gRPC client.

### PR DESCRIPTION
**Pull request by bianpengyuan**
I've tested that this works fine with real sd backend.

cc @williamaronli @howardjohn

### CODE REVIEW

**Comment by mandarjog** [comment]
Is this done because it is not necessary or because it does not work sometimes?

**Comment by bianpengyuan** [comment]
It does not work on some VM distro where system root is not at `/etc/ssl/certs/ca-certificates.crt`, such as centos. Google grpc already handled different root ca file path gracefully.

**Review by mandarjog — APPROVED** [review]
Lgtm

**Comment by howardjohn** [comment]
Just to verify, this means we will use system certs, right? Not that we
will not verify?

**Comment by bianpengyuan** [comment]
> Just to verify, this means we will use system certs, right? Not that we
will not verify?

Right. To double check, I removed the logic to set test root ca cert, and integration test fails:
```
E0318 15:32:41.284894724   19837 ssl_transport_security.cc:1446] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

**Pull request merged**
