### PR TITLE
update envoy to 7daff5027f20fc36a9d3a3c88d7eec545792d045

### PR DESCRIPTION
**Pull request by yangminzhu**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bianpengyuan** [comment]
I believe @gargnupur is doing the same? I think she mentioned there is some breaking change and build will fail with only sha update.

**Comment by gargnupur** [comment]
@bianpengyuan , @yangminzhu : Because of HeaderMap refactoring in base envoy, it needs to be updated in proxy too. I am trying to get all tests pass in my local branch first..
For ref: Here are the changes I have till now.. https://github.com/istio/proxy/compare/master...gargnupur:nup_update_sha?expand=1

**Comment by yangminzhu** [comment]
@bianpengyuan oh, didn't know @gargnupur is updating this, I will just close this one. Thanks for fixing the HeaderMap stuff!

**Comment by gargnupur** [comment]
@yangminzhu : PR for review https://github.com/istio/proxy/pull/2727

**Pull request closed without merging**
