### PR TITLE
upgrade envoy to latest

### PR DESCRIPTION
**Pull request by ramaraochavali**
This PR upgrades Envoy sha to the latest. We need this SHA specifically this PR https://github.com/envoyproxy/envoy/pull/7019 so that we can use the newly added header support.

### CODE REVIEW

**Comment by venilnoronha** [comment]
@ramaraochavali is the SHA from envoyproxy/envoy-wasm or envoyproxy/envoy?

**Comment by ramaraochavali** [comment]
@venilnoronha  It is `envoy-proxy/envoy-wasm` sha.

**Comment by ramaraochavali** [comment]
@lizan The build is failing with this error
`ERROR: Analysis of target '//tools/deb:istio-proxy' failed; build aborted: error loading package 'src/envoy': in /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/external/envoy/bazel/envoy_build_system.bzl: in /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/external/envoy/bazel/envoy_library.bzl: in /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/external/envoy_api/bazel/api_build_system.bzl: in /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/external/com_envoyproxy_protoc_gen_validate/bazel/pgv_proto_library.bzl: in /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/external/com_envoyproxy_protoc_gen_validate/bazel/protobuf.bzl: Unable to load file '@bazel_tools//tools/jdk:toolchain_utils.bzl': file doesn't exist`

Any idea?

**Comment by ramaraochavali** [comment]
I think after this PR https://github.com/envoyproxy/envoy/pull/7115 which protoc-gen validate this might be breaking. It is not able to load the jdk tool chain` @bazel_tools//tools/jdk:toolchain_utils.bzl'  - May need newer bazel? Currently it is using `0.22`. 

@PiotrSikora  Any thoughts?

**Comment by lizan** [comment]
0.22 doesn't work after that, can we use 0.26+?

**Comment by ramaraochavali** [comment]
@lizan Yeah. That is what I figured out. But I can't see bazel 0.26 version of this image `istio/ci:go1.11-bazel0.22-clang7-cmake3.8.0` - Do you know where is the source of this to upgrade?

**Comment by PiotrSikora** [comment]
> @venilnoronha It is `envoy-proxy/envoy-wasm` sha.

It's not. That commit exists there because it was merged from `envoyproxy/envoy`, but it's off-branch.

Please update to https://github.com/envoyproxy/envoy-wasm/commit/674411c3b9d363cef8e88c5604de09b95f0f965c.

> @lizan Yeah. That is what I figured out. But I can't see bazel 0.26 version of this image `istio/ci:go1.11-bazel0.22-clang7-cmake3.8.0` - Do you know where is the source of this to upgrade?

It's built using `make image` in `.circleci` directory.

cc @bianpengyuan who I think is also working on this.

**Comment by bianpengyuan** [comment]
I will send out a PR to update envoy SHA shortly.

**Comment by bianpengyuan** [comment]
@ramaraochavali https://github.com/istio/proxy/pull/2286 updates the sha and should have your desired change.

**Comment by ramaraochavali** [comment]
@PiotrSikora Thank you. I initially upgraded to `envoyproxy/envoy-wasm@674411c.` but ended up errors because of bazel and ended up with the sha in PR as trial and error.

> It's built using make image in .circleci directory.
Thank you. This is useful.

@bianpengyuan I will close this PR in favour of your PR. Thanks for upgrading.

**Pull request closed without merging**
