### PR TITLE
update extensions doc

### PR DESCRIPTION
**Pull request by zirain**
update https://istio.io/latest/docs/reference/config/proxy_extensions/stats/

### CODE REVIEW

**Review by lei-tang — APPROVED** [review]

**Comment by zirain** [comment]
https://deploy-preview-12312--preliminary-istio.netlify.app/latest/docs/reference/config/proxy_extensions/stats/

cherry-pick to v1.16

/cherrypick release-1.16

**Comment by ericvn** [comment]
Question is if we updated the format of items such as:
```
- <td><code>log_window_duration</code></td>
+ <td><code>logWindowDuration</code></td>
```
Which I am noting in the new update reference docs: https://github.com/istio/istio.io/pull/12348

**Comment by ericvn** [comment]
@kyessenov Noted in Slack that this change was a mistake: `Wasm extensions like MX parse as JSON and can't handle camelCase.`

There needs to be another update to fix that.

**Pull request merged**
