### PR TITLE
Use Bazelisk launcher for Bazel.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Could someone push `istio/ci:go1.11-bazelisk-clang8-cmake3.8.0` to DockerHub, since I don't have access? Thanks!

**Comment by PiotrSikora** [comment]
> Add a `.bazelversion` file too?

Sigh. That's the most important part... and it looks that I forgot to `git add` it.

Thanks for catching it!

**Comment by bianpengyuan** [comment]
I lost my push accessibility recently, sorry! I am not sure who in the review list would have the ability to push. @mandarjog are you the owner of that docker repo?

**Comment by PiotrSikora** [comment]
@duderino can you figure out who has access to push CircleCI images to `istio/ci` (and, ideally, grant it to me)?

**Comment by PiotrSikora** [comment]
/hold

(I'm going to update Prow to the new `prowbazel` images first)

**Pull request merged**
