### PR TITLE
Create child spans for mixer check calls

### PR DESCRIPTION
**Pull request by bianpengyuan**

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Now tracing looks like this:
screen shot 2018-04-27 at 11 53 33 pm

cc @douglas-reid @kyessenov

**Comment by mandarjog** [comment]
This seems odd. The labels say “report” while calling istio-policy, should say check?

**Comment by bianpengyuan** [comment]
@mandarjog Yes, that is a separated problem. I am going to fix it as well, and I think the problem is in policy's sidecar config?

**Comment by kyessenov** [comment]
@mandarjog Yes, that's a bug. Check/Report are swapped: https://github.com/istio/istio/blob/master/pilot/docker/envoy_telemetry.yaml.tmpl

**Comment by kyessenov** [comment]
PR out https://github.com/istio/istio/pull/5283

**Comment by kyessenov** [comment]
Why is there two Check calls on the first hop?

**Comment by bianpengyuan** [comment]
@kyessenov One from Ingress and one from productpage sidecar.

**Comment by douglas-reid** [comment]
Reminder: These PRs should be against the 0.8 release branch, instead of master. Please re-open against the correct branch (as master is now locked).

**Comment by douglas-reid** [comment]
Should ingress itself also not have a span?

**Comment by kyessenov** [comment]
Yes, ingress tracing has issues, too, I think. My expectation is that the
check should be on a span that reaches ingress service, not the outbound
call from ingress. That's not how it looks on the chart. Additionally, we
should probably try a gateway as well.

**Comment by bianpengyuan** [comment]
Close this one with another one open in 0.8 branch: #1610

**Pull request closed without merging**
