### PR TITLE
fix(stackdriver): support turning off http size metrics

### PR DESCRIPTION
**Pull request by douglas-reid**
This PR adds configurability to the Stackdriver metrics plugin. It allows disabling of all request/response bytes metrics.

Signed-off-by: Douglas Reid <douglas-reid@users.noreply.github.com>

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Regarding disable outbound filter, since outbound metrics are the only telemetry reported on the way out, does it make more sense to add an option to istioctl values instead? The value will just avoid deploying the outbound filter.

**Comment by douglas-reid** [comment]
@bianpengyuan that's a good question, and an interesting idea. i wonder though: doesn't that make it more of an install time option?

**Comment by kyessenov** [comment]
I prefer Peter's suggestion. We could split envoyfilters into client and server side config resources. Then it's a matter of `kubectl delete envoyfilter stackdriver-outbound`.

**Comment by douglas-reid** [comment]
@kyessenov that certain simplifies the code. how well does this align with the future non-EnvoyFilter-based feature enablement?

**Comment by kyessenov** [comment]
We should keep separating client vs server extension configs for non-EnvoyFilter based approach.

**Comment by douglas-reid** [comment]
Thanks for the great feedback so far. I've removed the toggle for client-side metrics and have added/updated tests.

**Comment by bianpengyuan** [comment]
Asan failure should relate to the change.

**Comment by mandarjog** [comment]
Ping ! We should get this in @douglas-reid

**Pull request merged**
