### PR TITLE
Use v4only for CircleCI

### PR DESCRIPTION
**Pull request by lizan**
**What this PR does / why we need it**:
Fix CircleCI presubmit failure

**Which issue this PR fixes*

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by qiwzhang** [comment]
@lizan Hmm,   config=clang-tsan failed.  Any ideas?

**Comment by lizan** [comment]
clang-tsan doens't work since the ci image doesn't have clang, we're building clang-tsan with gcc and it fails.

**Comment by qiwzhang** [comment]
@lizan could you remove clang-tsan in circleci?

**Pull request merged**
