### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Still debugging wasm build issue.

### CODE REVIEW

**Review by lambdai — APPROVED** [review]
This PR should have fixed the envoy binary build. Thank you!

**Comment by kyessenov** [comment]
Somehow abseil override is not picked up by wasm targets. Busting the cache and waiting 4 more hours for another build...

**Comment by kyessenov** [comment]
Failure in TCP stack driver extension. Need more debugging.

**Comment by kyessenov** [comment]
Something is wrong with HTTP inspector, likely culprit is https://github.com/envoyproxy/envoy/pull/17395.

**Review by zirain — APPROVED** [review]
thanks!

**Comment by ericvn** [comment]
Thanks. Looks like we know have an issue getting this into istio/istio: https://github.com/istio/istio/pull/38310.

**Pull request merged**
