### PR TITLE
use absl::StatusOr

### PR DESCRIPTION
**Pull request by zirain**
fixes: https://github.com/istio/proxy/pull/5149

xref: https://github.com/envoyproxy/envoy/pull/30765

### CODE REVIEW

**Comment by kyessenov** [comment]
Can you make sure there are no exceptions as well? StatusOr is meant to replace exceptions.

**Comment by zirain** [comment]
> Can you make sure there are no exceptions as well? StatusOr is meant to replace exceptions.

I change this because of https://github.com/envoyproxy/envoy/pull/30765, I don't think need any logic change.

**Review by kyessenov — APPROVED** [review]

**Comment by kyessenov** [comment]
/retest

I think it's starting to flake locally too, so maybe we should finally root cause it.

**Comment by zirain** [comment]
can we make these optional before figure out what happen?

**Comment by kyessenov** [comment]
Yeah, put SkipTsanAsan on the test TestStackdriverRbacTCPDryRun, it'll let this merge. The test fails on non-Asan so it's just a borked test probably.

**Comment by zirain** [comment]
open https://github.com/istio/test-infra/pull/5093

**Pull request merged**
