### PR TITLE
Fix logging in mixer_fault_test

### PR DESCRIPTION
**Pull request by dmitri-d**
…with cli '-l' option

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kyessenov** [comment]
Seems reasonable.
/lgtm
/approve

**Comment by dmitri-d** [comment]
@duderino: you may have fixed this in your copy already. 

Explicit log-level in tests was resetting cli option I was passing to bazel via ```test_arg```: 
```
bazel  test -c opt --test_arg="-l trace" //test/integration:mixer_fault_test
```

**Comment by dmitri-d** [comment]
Opened a PR with these changes against master branch, closing this one.

**Pull request closed without merging**
