### PR TITLE
Update Envoy SHA.

### PR DESCRIPTION
**Pull request by bianpengyuan**
Supersedes https://github.com/istio/proxy/pull/3365

### CODE REVIEW

**Review by kyessenov — APPROVED** [review]

**Comment by kyessenov** [comment]
Is the compiler error some c++20 thingy?

**Comment by lambdai** [comment]
Awesome!

**Comment by lambdai** [comment]
There was a guidance on when to use absl::string_view and std::string_view in envoy

**Comment by lambdai** [comment]
Mostly importantly it's a breaking change: https://github.com/envoyproxy/envoy/pull/16029

**Pull request closed without merging**
