### PR TITLE
fixes envoy commit sha256

### PR DESCRIPTION
**Pull request by ajayk**
**What this PR does / why we need it**:
WORKSPACE has wrong sha256 for envoy commit 3e6e83d166c2ec70aa07a60be088ac76a60734a9 fixes build issues 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes build issues 
```
2024/02/09 18:41:30 WARN Repository rule http_archive defined at: arch=x86_64
2024/02/09 18:41:30 WARN   /home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel> arch=x86_64
2024/02/09 18:41:30 WARN WARNING: Download from https://github.com/istio/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540 but wanted de0e61e908a6dd5e27271e7c1482b1f11d364b7fddb2481adfeed1a1ce4096af arch=x86_64
2024/02/09 18:41:30 WARN ERROR: An error occurred during the fetch of repository 'envoy': arch=x86_64
2024/02/09 18:41:30 WARN    Traceback (most recent call last): arch=x86_64
2024/02/09 18:41:30 WARN     File "/home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl arch=x86_64
2024/02/09 18:41:30 WARN         download_info = ctx.download_and_extract( arch=x86_64
2024/02/09 18:41:30 WARN Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/istio/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz] to /home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/envoy/temp12741509584241128482/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz: Checksum was 505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540 but wanted de0e61e908a6dd5e27271e7c1482b1f11d364b7fddb2481adfeed1a1ce4096af arch=x86_64
2024/02/09 18:41:30 WARN ERROR: /home/build/WORKSPACE:48:13: fetching http_archive rule //external:envoy: Traceback (most recent call last): arch=x86_64
2024/02/09 18:41:30 WARN     File "/home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl arch=x86_64
2024/02/09 18:41:30 WARN         download_info = ctx.download_and_extract( arch=x86_64
2024/02/09 18:41:30 WARN Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/istio/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz] to /home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/envoy/temp12741509584241128482/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz: Checksum was 505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540 but wanted de0e61e908a6dd5e27271e7c1482b1f11d364b7fddb2481adfeed1a1ce4096af arch=x86_64
2024/02/09 18:41:30 WARN ERROR: Error computing the main repository mapping: no such package '@envoy//bazel': java.io.IOException: Error downloading [https://github.com/istio/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz] to /home/build/.cache/bazel/_bazel_root/79a1bfc8c8b5b6a6d226b38d072f165b/external/envoy/temp12741509584241128482/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz: Checksum was 505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540 but wanted de0e61e908a6dd5e27271e7c1482b1f11d364b7fddb2481adfeed1a1ce4096af arch=x86_64
2024/02/09 18:41:30 WARN  arch=x86_64
```

**Special notes for your reviewer**:
```

 export ENVOY_SHA=3e6e83d166c2ec70aa07a60be088ac76a60734a9
# ./scripts/update_envoy.sh
+ UPDATE_BRANCH=main
+ ENVOY_SHA=3e6e83d166c2ec70aa07a60be088ac76a60734a9
+++ dirname ./scripts/update_envoy.sh
++ cd ./scripts/..
++ pwd -P
+ ROOT=/proxy
+ WORKSPACE=/proxy/WORKSPACE
++ grep -Pom1 '^ENVOY_ORG = "\K[a-zA-Z-]+' /proxy/WORKSPACE
+ ENVOY_ORG=envoyproxy
++ grep -Pom1 '^ENVOY_REPO = "\K[a-zA-Z-]+' /proxy/WORKSPACE
+ ENVOY_REPO=envoy
++ git ls-remote https://github.com/envoyproxy/envoy refs/heads/main
++ awk '{ print $1}'
+ LATEST_SHA=29989f6cc8bfd8cd2ffcb7c42711eb02c7a5168a
+ [[ -n 3e6e83d166c2ec70aa07a60be088ac76a60734a9 ]]
+ LATEST_SHA=3e6e83d166c2ec70aa07a60be088ac76a60734a9
++ curl -s -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/envoyproxy/envoy/commits/3e6e83d166c2ec70aa07a60be088ac76a60734a9
++ jq .commit.committer.date
+ DATE='"2024-01-27T17:17:18Z"'
++ echo '2024-01-27T17:17:18Z"'
++ cut -dT -f1
+ DATE=2024-01-27
+ URL=https://github.com/envoyproxy/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz
++ wget https://github.com/envoyproxy/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz
--2024-02-09 19:11:21--  https://github.com/envoyproxy/envoy/archive/3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/envoyproxy/envoy/tar.gz/3e6e83d166c2ec70aa07a60be088ac76a60734a9 [following]
--2024-02-09 19:11:21--  https://codeload.github.com/envoyproxy/envoy/tar.gz/3e6e83d166c2ec70aa07a60be088ac76a60734a9
Resolving codeload.github.com (codeload.github.com)... 140.82.114.10
Connecting to codeload.github.com (codeload.github.com)|140.82.114.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz'

3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz     [           <=>                                                                                       ]  22.21M  10.5MB/s    in 2.1s    

2024-02-09 19:11:23 (10.5 MB/s) - '3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz' saved [23293412]

++ sha256sum 3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz
++ awk '{ print $1 }'
+ GETSHA=505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540
+ SHAArr=("${GETSHA}")
+ SHA256=505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540
+ rm 3e6e83d166c2ec70aa07a60be088ac76a60734a9.tar.gz
+ sed -i 's/Commit date: .*/Commit date: 2024-01-27/' /proxy/WORKSPACE
+ sed -i 's/ENVOY_SHA = .*/ENVOY_SHA = "3e6e83d166c2ec70aa07a60be088ac76a60734a9"/' /proxy/WORKSPACE
+ sed -i 's/ENVOY_SHA256 = .*/ENVOY_SHA256 = "505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540"/' /proxy/WORKSPACE
+ curl -sSL https://raw.githubusercontent.com/envoyproxy/envoy/3e6e83d166c2ec70aa07a60be088ac76a60734a9/.bazelversion
+ curl -sSL https://raw.githubusercontent.com/envoyproxy/envoy/3e6e83d166c2ec70aa07a60be088ac76a60734a9/.bazelrc
# git diff
diff --git a/WORKSPACE b/WORKSPACE
index 07b36d1c..b391315c 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -22,10 +22,10 @@ load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 # 1. Determine SHA256 `wget https://github.com/envoyproxy/envoy/archive/$COMMIT.tar.gz && sha256sum $COMMIT.tar.gz`
 # 2. Update .bazelversion, envoy.bazelrc and .bazelrc if needed.
 #
-# Commit date: 2024-02-09
-ENVOY_SHA = "cfbc5ebb3b7b4423f203c2b348294b0820e049a1"
+# Commit date: 2024-01-27
+ENVOY_SHA = "3e6e83d166c2ec70aa07a60be088ac76a60734a9"
 
-ENVOY_SHA256 = "686b724bafe6408e36ed1540763ead3e01b5bd495d1869ba5b4c0e47718d87c9"
+ENVOY_SHA256 = "505056137453f5fa57fad9c20d9bfcf2290ad6dc229030c42dd20cbd7d300540"
```

### CODE REVIEW

**Comment by hanxiaop** [comment]
Similar question to https://github.com/istio/proxy/pull/5319#issuecomment-1945295032

**Comment by zirain** [comment]
we don't update a patch branch

**Comment by leerin-ruby** [comment]
@zirain 
there is no branch 1.20.3, if this fix can't commit how to fix this build error for istio proxy build on version 1.20.3?

**Comment by zirain** [comment]
@lgadban can you take a look, looks like the sha256 is wrong?

**Comment by lgadban** [comment]
@zirain Yes, I am actively investigating, will report back as soon as I know more!

**Comment by lgadban** [comment]
Due to the build issue, we actually should merge this.
More info: https://github.com/istio/istio/issues/49561

**Comment by ajayk** [comment]
Thanks @lgadban I had another PR here  https://github.com/istio/proxy/pull/5319

**Comment by lgadban** [comment]
Sorry @ajayk I missed that PR; it is already addressed here: https://github.com/istio/proxy/pull/5362

**Pull request merged**
