### PR TITLE
merge release-1.1 to master

### PR DESCRIPTION
**Pull request by lizan**
**What this PR does / why we need it**:

To unblock istio/istio#12434

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by rshriram** [comment]
fix build

**Comment by lizan** [comment]
@duderino mixer_fault_test is failing like this:

```
[ RUN      ] MixerFaultTest.RetryOnTransportError
test/integration/mixer_fault_test.cc:1004: Failure
Expected equality of these values:
  counters["http_mixer_filter.total_remote_call_other_errors"]
    Which is: 450
  0
test/integration/mixer_fault_test.cc:1020: Failure
Expected: (counters["http_mixer_filter.total_remote_call_send_errors"]) >= (requests_to_send / 2 - requests_to_send / 10), actual: 0 vs 360
[  FAILED  ] MixerFaultTest.RetryOnTransportError (7574 ms)
```

Any idea?

**Comment by lizan** [comment]
@duderino ok it should be now fixed, can you modify CLA?

**Comment by kyessenov** [comment]
@rshriram can you not squash merge commits? It's not about the credit but making it difficult to track changes against issues/PRs.

cc @duderino

**Comment by kyessenov** [comment]
Apologize, misread the git history.

**Pull request merged**
