### PR TITLE
Make extension doc generates snake case.

### PR DESCRIPTION
**Pull request by bianpengyuan**
Proxy extension is configured with snake case field name instead of camel case. Update doc gen to clarify it.

### CODE REVIEW

**Review by richardwxn — APPROVED** [review]

**Review by PiotrSikora — APPROVED** [review]

**Comment by ericvn** [comment]
Does this also need to be cherry-picked back to 1.9?

**Comment by bianpengyuan** [comment]
Yeah sure added several cherry-pick labels.

**Comment by bianpengyuan** [comment]
@istio/wg-policies-and-telemetry-maintainers please take a look, thanks!

**Comment by bianpengyuan** [comment]
@istio/wg-policies-and-telemetry-maintainers please take a look, thanks!

**Review by mandarjog — APPROVED** [review]
lgtm

**Pull request merged**
