### PR TITLE
fix commonfile lint

### PR DESCRIPTION
**Pull request by zirain**
unblock https://github.com/istio/proxy/pull/4339

### CODE REVIEW

**Comment by ericvn** [comment]
Here is the lint I saw:
```
test/envoye2e/driver/scenario.go:27:2: `github.com/golang/protobuf/jsonpb` is in the denylist: don't use the jsonpb package directly; use util/protomarshal instead (depguard)
	"github.com/golang/protobuf/jsonpb" // nolint: depguard - We need the deprecated module since the jsonpb replacement is not backwards compatible.
	^
test/envoye2e/stackdriver_plugin/fake_stackdriver.go:33:2: `github.com/golang/protobuf/jsonpb` is in the denylist: don't use the jsonpb package directly; use util/protomarshal instead (depguard)
	"github.com/golang/protobuf/jsonpb"
	^
```

I'm creating another PR with both.

**Comment by lei-tang** [comment]
@ericvn Is the issue in this PR fixed by one of your PRs? If so, can you add a link of your PR?

**Review by lei-tang — COMMENTED** [review]
@ericvn Is the issue in this PR fixed by one of your PRs? If so, can you add a link of your PR?

**Comment by ericvn** [comment]
This was superseded by https://github.com/istio/proxy/pull/4341.

**Pull request closed without merging**
