### PR TITLE
remove ambient extensions

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Since these are not tested and don't receive work to promote further, delete them to prevent tech debt.
Can be recovered from git if needed.

/assign @stevenctl

### CODE REVIEW

**Review by stevenctl — COMMENTED** [review]
Do we have them on some other branch or are we relying on git history?

For the ambient experimental branch we need to temporarily pin to a version of envoy that has these.

**Comment by kyessenov** [comment]
Well, the author is gone so git history is the best we can do. Ambient branch is already pinned, we already replaced a couple of extensions.

**Review by zirain — APPROVED** [review]
@stevenctl feel free to remove `DNM`

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
