### PR TITLE
Update Envoy-WASM SHA to latest.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Blocked on https://github.com/istio/test-infra/pull/1493 and https://github.com/istio/test-infra/pull/1494 (for Prow) and someone uploading new Docker images (for Linux on CircleCI).

Alternatively, can someone add me to the DockerHub? cc @bianpengyuan @mandarjog

**Comment by bianpengyuan** [comment]
Circle image pushed.

**Comment by PiotrSikora** [comment]
@bianpengyuan thanks!

**Comment by PiotrSikora** [comment]
/hold

Please don't merge this until Prow is updated (https://github.com/istio/test-infra/pull/1493, https://github.com/istio/test-infra/pull/1494), otherwise we're going to end up with broken daily builds (tests pass now [because we don't run upstream tests](https://github.com/istio/proxy/issues/2256), but the binaries are corrupted with Bazel 0.27).

**Comment by PiotrSikora** [comment]
Prow images updated, this should be good to go.

**Comment by bianpengyuan** [comment]
@silentdai Can you help to approve? Thanks!

**Comment by silentdai** [comment]
@bianpengyuan 
Could you confirm if proxy can survive despite my comment below?
https://github.com/envoyproxy/envoy-wasm/commit/f81e02649420e4ba9f3b5b61074948d9bf741f83#r34345829

**Comment by PiotrSikora** [comment]
@silentdai good catch, see: https://github.com/envoyproxy/envoy/pull/7623.

**Comment by silentdai** [comment]
:+1: That works :)

**Comment by PiotrSikora** [comment]
Bumped to include https://github.com/envoyproxy/envoy/pull/7623, @silentdai PTAL.

**Comment by silentdai** [comment]
/lgtm

Thank you for fixing at upstream!

/approve

**Pull request merged**
