### PR TITLE
Make TCP workload metadata writable

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**: https://github.com/istio/istio/issues/28122

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kyessenov — APPROVED** [review]
Can you document in the PR description what issue this change solves?

**Comment by bianpengyuan** [comment]
@kyessenov Added the issue.

**Review by gargnupur — APPROVED** [review]

**Comment by bianpengyuan** [comment]
Tsan failure seems to be caused by race condition from upstream:
```
[2020-10-20 23:57:54.294][76408][info][main] [external/envoy/source/server/server.cc:731] exiting
==================
WARNING: ThreadSanitizer: data race (pid=76408)
  Atomic write of size 4 at 0x7f62d66ca150 by main thread:
    #0 __tsan_atomic32_fetch_add <null> (envoy+0x4fc5969)
    #1 int std::__1::__cxx_atomic_fetch_add<int>(std::__1::__cxx_atomic_base_impl<int>*, int, std::__1::memory_order) <null> (envoy+0x5bc58bb)
    #2 std::__1::__atomic_base<int, true>::fetch_add(int, std::__1::memory_order) <null> (envoy+0x5bc57f0)
    #3 absl::synchronization_internal::Waiter::Post() <null> (envoy+0xddd03bc)
    #4 AbslInternalPerThreadSemPost <null> (envoy+0xddcf790)
    #5 absl::synchronization_internal::PerThreadSem::Post(absl::base_internal::ThreadIdentity*) <null> (envoy+0xddcba38)
    #6 absl::Mutex::IncrementSynchSem(absl::Mutex*, absl::base_internal::PerThreadSynch*) <null> (envoy+0xddcae2c)
    #7 absl::Mutex::Wakeup(absl::base_internal::PerThreadSynch*) <null> (envoy+0xddbe9cd)
    #8 absl::Mutex::UnlockSlow(absl::SynchWaitParams*) <null> (envoy+0xddc27cc)
    #9 absl::Mutex::Unlock() <null> (envoy+0xddc495d)
    #10 Envoy::Thread::MutexBasicLockable::unlock() <null> (envoy+0x566188f)
    #11 Envoy::Thread::LockGuard::~LockGuard() <null> (envoy+0x5b2c342)
    #12 Envoy::AccessLog::AccessLogFileImpl::~AccessLogFileImpl() <null> (envoy+0xa770741)
    #13 std::__1::__shared_ptr_emplace<Envoy::AccessLog::AccessLogFileImpl, std::__1::allocator<Envoy::AccessLog::AccessLogFileImpl> >::__on_zero_shared() <null> (envoy+0xa77f34d)
    #14 std::__1::__shared_count::__release_shared() <null> (envoy+0x4fef55c)
    #15 std::__1::__shared_weak_count::__release_shared() <null> (envoy+0x4fef4d2)
    #16 std::__1::shared_ptr<Envoy::AccessLog::AccessLogFile>::~shared_ptr() <null> (envoy+0x56f70f7)
    #17 Envoy::Extensions::AccessLoggers::File::FileAccessLog::~FileAccessLog() <null> (envoy+0x56f7077)
    #18 Envoy::Extensions::AccessLoggers::File::FileAccessLog::~FileAccessLog() <null> (envoy+0xb28c68f)
    #19 std::__1::default_delete<Envoy::Extensions::AccessLoggers::File::FileAccessLog>::operator()(Envoy::Extensions::AccessLoggers::File::FileAccessLog*) const <null> (envoy+0xb1c05a6)
    #20 std::__1::__shared_ptr_pointer<Envoy::Extensions::AccessLoggers::File::FileAccessLog*, std::__1::default_delete<Envoy::Extensions::AccessLoggers::File::FileAccessLog>, std::__1::allocator<Envoy::Extensions::AccessLoggers::File::FileAccessLog> >::__on_zero_shared() <null> (envoy+0xb1c022f)
    #21 std::__1::__shared_count::__release_shared() <null> (envoy+0x4fef55c)
    #22 std::__1::__shared_weak_count::__release_shared() <null> (envoy+0x4fef4d2)
    #23 std::__1::shared_ptr<Envoy::AccessLog::Instance>::~shared_ptr() <null> (envoy+0x63639d7)
    #24 void std::__1::allocator_traits<std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<Envoy::AccessLog::Instance>, void*> > >::__destroy<std::__1::shared_ptr<Envoy::AccessLog::Instance> >(std::__1::integral_constant<bool, false>, std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<Envoy::AccessLog::Instance>, void*> >&, std::__1::shared_ptr<Envoy::AccessLog::Instance>*) <null> (envoy+0x63653b4)
    #25 void std::__1::allocator_traits<std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<Envoy::AccessLog::Instance>, void*> > >::destroy<std::__1::shared_ptr<Envoy::AccessLog::Instance> >(std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<Envoy::AccessLog::Instance>, void*> >&, std::__1::shared_ptr<Envoy::AccessLog::Instance>*) <null> (envoy+0x63651c8)
    #26 std::__1::__list_imp<std::__1::shared_ptr<Envoy::AccessLog::Instance>, std::__1::allocator<std::__1::shared_ptr<Envoy::AccessLog::Instance> > >::clear() <null> (envoy+0x6364e9b)
    #27 std::__1::__list_imp<std::__1::shared_ptr<Envoy::AccessLog::Instance>, std::__1::allocator<std::__1::shared_ptr<Envoy::AccessLog::Instance> > >::~__list_imp() <null> (envoy+0x6364d58)
    #28 std::__1::list<std::__1::shared_ptr<Envoy::AccessLog::Instance>, std::__1::allocator<std::__1::shared_ptr<Envoy::AccessLog::Instance> > >::~list() <null> (envoy+0x636411b)
    #29 Envoy::Server::AdminImpl::~AdminImpl() <null> (envoy+0xb1b0573)
    #30 Envoy::Server::AdminImpl::~AdminImpl() <null> (envoy+0xb1b061f)
    #31 std::__1::default_delete<Envoy::Server::AdminImpl>::operator()(Envoy::Server::AdminImpl*) const <null> (envoy+0xa6d43c6)
    #32 std::__1::unique_ptr<Envoy::Server::AdminImpl, std::__1::default_delete<Envoy::Server::AdminImpl> >::reset(Envoy::Server::AdminImpl*) <null> (envoy+0xa6d42e0)
    #33 std::__1::unique_ptr<Envoy::Server::AdminImpl, std::__1::default_delete<Envoy::Server::AdminImpl> >::~unique_ptr() <null> (envoy+0xa6c2d5c)
    #34 Envoy::Server::InstanceImpl::~InstanceImpl() <null> (envoy+0xa686e9d)
    #35 Envoy::Server::InstanceImpl::~InstanceImpl() <null> (envoy+0xa68738f)
    #36 std::__1::default_delete<Envoy::Server::InstanceImpl>::operator()(Envoy::Server::InstanceImpl*) const <null> (envoy+0x56683c6)
    #37 std::__1::unique_ptr<Envoy::Server::InstanceImpl, std::__1::default_delete<Envoy::Server::InstanceImpl> >::reset(Envoy::Server::InstanceImpl*) <null> (envoy+0x56682e0)
    #38 std::__1::unique_ptr<Envoy::Server::InstanceImpl, std::__1::default_delete<Envoy::Server::InstanceImpl> >::~unique_ptr() <null> (envoy+0x565e68c)
    #39 Envoy::MainCommonBase::~MainCommonBase() <null> (envoy+0x5687409)
    #40 Envoy::MainCommon::~MainCommon() <null> (envoy+0x5687349)
    #41 std::__1::default_delete<Envoy::MainCommon>::operator()(Envoy::MainCommon*) const <null> (envoy+0x56872d6)
    #42 std::__1::unique_ptr<Envoy::MainCommon, std::__1::default_delete<Envoy::MainCommon> >::reset(Envoy::MainCommon*) <null> (envoy+0x5687200)
    #43 std::__1::unique_ptr<Envoy::MainCommon, std::__1::default_delete<Envoy::MainCommon> >::~unique_ptr() <null> (envoy+0x566051c)
    #44 Envoy::MainCommon::main(int, char**, std::__1::function<void (Envoy::Server::Instance&)>) <null> (envoy+0x565a00e)
    #45 main <null> (envoy+0x5656415)
  Previous write of size 8 at 0x7f62d66ca150 by thread T7:
    #0 mmap <null> (envoy+0x4fa9cba)
    #1 absl::base_internal::DoAllocWithArena(unsigned long, absl::base_internal::LowLevelAlloc::Arena*) <null> (envoy+0xddf22c6)
    #2 absl::base_internal::LowLevelAlloc::Alloc(unsigned long) <null> (envoy+0xde5c91a)
    #3 absl::synchronization_internal::NewThreadIdentity() <null> (envoy+0xddcfc89)
    #4 absl::synchronization_internal::CreateThreadIdentity() <null> (envoy+0xddcfb65)
    #5 absl::synchronization_internal::GetOrCreateCurrentThreadIdentity() <null> (envoy+0xddcb966)
    #6 absl::Synch_GetPerThread() <null> (envoy+0xddc87c5)
    #7 absl::Synch_GetPerThreadAnnotated(absl::Mutex*) <null> (envoy+0xddc0a44)
    #8 absl::CondVar::WaitCommon(absl::Mutex*, absl::synchronization_internal::KernelTimeout) <null> (envoy+0xddc701d)
    #9 absl::CondVar::Wait(absl::Mutex*) <null> (envoy+0xddc7582)
    #10 Envoy::Thread::CondVar::wait(Envoy::Thread::MutexBasicLockable&) <null> (envoy+0xa77847f)
    #11 Envoy::AccessLog::AccessLogFileImpl::flushThreadFunc() <null> (envoy+0xa77173c)
    #12 Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1::operator()() const <null> (envoy+0xa7776db)
    #13 decltype(std::__1::forward<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1&>(fp)()) std::__1::__invoke<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1&>(Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1&) <null> (envoy+0xa777660)
    #14 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1&>(Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1&) <null> (envoy+0xa7775c0)
    #15 std::__1::__function::__alloc_func<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1, std::__1::allocator<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1>, void ()>::operator()() <null> (envoy+0xa777560)
    #16 std::__1::__function::__func<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1, std::__1::allocator<Envoy::AccessLog::AccessLogFileImpl::createFlushStructures()::$_1>, void ()>::operator()() <null> (envoy+0xa775bbf)
    #17 std::__1::__function::__value_func<void ()>::operator()() const <null> (envoy+0x52e2876)
    #18 std::__1::function<void ()>::operator()() const <null> (envoy+0x52e27c8)
    #19 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::operator()(void*) const <null> (envoy+0xc47e90b)
    #20 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) <null> (envoy+0xc47e898)
  Thread T7 'AccessLogFlush' (tid=76911, running) created by main thread at:
    #0 pthread_create <null> (envoy+0x4f797cb)
    #1 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&) <null> (envoy+0xc47c55b)
    #2 std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, std::__1::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, std::__1::optional<Envoy::Thread::Options> const&) <null> (envoy+0xc47bcaf)
    #3 Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&) <null> (envoy+0xc47b9f3)
    #4 Envoy::AccessLog::AccessLogFileImpl::createFlushStructures() <null> (envoy+0xa772d65)
    #5 Envoy::AccessLog::AccessLogFileImpl::write(std::__1::basic_string_view<char, std::__1::char_traits<char> >) <null> (envoy+0xa772a92)
    #6 Envoy::Extensions::AccessLoggers::File::FileAccessLog::emitLog(Envoy::Http::RequestHeaderMap const&, Envoy::Http::ResponseHeaderMap const&, Envoy::Http::ResponseTrailerMap const&, Envoy::StreamInfo::StreamInfo const&) <null> (envoy+0xb28c398)
    #7 Envoy::Extensions::AccessLoggers::Common::ImplBase::log(Envoy::Http::RequestHeaderMap const*, Envoy::Http::ResponseHeaderMap const*, Envoy::Http::ResponseTrailerMap const*, Envoy::StreamInfo::StreamInfo const&) <null> (envoy+0xb28c9f3)
    #8 Envoy::Http::FilterManager::log() <null> (envoy+0xb562a7f)
    #9 Envoy::Http::ConnectionManagerImpl::doDeferredStreamDestroy(Envoy::Http::ConnectionManagerImpl::ActiveStream&) <null> (envoy+0xb52b436)
    #10 Envoy::Http::ConnectionManagerImpl::doEndStream(Envoy::Http::ConnectionManagerImpl::ActiveStream&) <null> (envoy+0xb52b0a0)
    #11 Envoy::Http::ConnectionManagerImpl::ActiveStream::endStream() <null> (envoy+0xb56ae6c)
    #12 non-virtual thunk to Envoy::Http::ConnectionManagerImpl::ActiveStream::endStream() <null> (envoy+0xb56b90f)
    #13 Envoy::Http::FilterManager::maybeEndEncode(bool) <null> (envoy+0xb5ac545)
    #14 Envoy::Http::FilterManager::encodeData(Envoy::Http::ActiveStreamEncoderFilter*, Envoy::Buffer::Instance&, bool, Envoy::Http::FilterManager::FilterIterationStartState) <null> (envoy+0xb5a517c)
    #15 Envoy::Http::ActiveStreamDecoderFilter::encodeData(Envoy::Buffer::Instance&, bool) <null> (envoy+0xb5a38f7)
    #16 non-virtual thunk to Envoy::Http::ActiveStreamDecoderFilter::encodeData(Envoy::Buffer::Instance&, bool) <null> (envoy+0xb5a534f)
    #17 Envoy::Server::AdminFilter::onComplete() <null> (envoy+0xb1d1be4)
    #18 Envoy::Server::AdminFilter::decodeHeaders(Envoy::Http::RequestHeaderMap&, bool) <null> (envoy+0xb1d0868)
    #19 Envoy::Http::ActiveStreamDecoderFilter::decodeHeaders(Envoy::Http::RequestHeaderMap&, bool) <null> (envoy+0xb5d6503)
    #20 Envoy::Http::FilterManager::decodeHeaders(Envoy::Http::ActiveStreamDecoderFilter*, Envoy::Http::RequestHeaderMap&, bool) <null> (envoy+0xb597933)
    #21 Envoy::Http::FilterManager::decodeHeaders(Envoy::Http::RequestHeaderMap&, bool) <null> (envoy+0xb567b46)
    #22 Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::__1::unique_ptr<Envoy::Http::RequestHeaderMap, std::__1::default_delete<Envoy::Http::RequestHeaderMap> >&&, bool) <null> (envoy+0xb5403a8)
    #23 non-virtual thunk to Envoy::Http::ConnectionManagerImpl::ActiveStream::decodeHeaders(std::__1::unique_ptr<Envoy::Http::RequestHeaderMap, std::__1::default_delete<Envoy::Http::RequestHeaderMap> >&&, bool) <null> (envoy+0xb54165f)
    #24 Envoy::Http::Legacy::Http1::ServerConnectionImpl::onMessageComplete() <null> (envoy+0xb5fe6d5)
    #25 non-virtual thunk to Envoy::Http::Legacy::Http1::ServerConnectionImpl::onMessageComplete() <null> (envoy+0xb5fe9ff)
    #26 Envoy::Http::Legacy::Http1::ConnectionImpl::onMessageCompleteBase() <null> (envoy+0xb5f995b)
    #27 Envoy::Http::Legacy::Http1::ConnectionImpl::$_8::operator()(http_parser*) const <null> (envoy+0xb60720f)
    #28 Envoy::Http::Legacy::Http1::ConnectionImpl::$_8::__invoke(http_parser*) <null> (envoy+0xb5efd78)
    #29 http_parser_execute <null> (envoy+0xbe6480e)
    #30 Envoy::Http::Legacy::Http1::ConnectionImpl::dispatchSlice(char const*, unsigned long) <null> (envoy+0xb5f4cf9)
    #31 Envoy::Http::Legacy::Http1::ConnectionImpl::innerDispatch(Envoy::Buffer::Instance&) <null> (envoy+0xb5f3d18)
    #32 Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14::operator()(Envoy::Buffer::Instance&) const <null> (envoy+0xb614d42)
    #33 decltype(std::__1::forward<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14&>(fp)(std::__1::forward<Envoy::Buffer::Instance&>(fp0))) std::__1::__invoke<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14&, Envoy::Buffer::Instance&>(Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14&, Envoy::Buffer::Instance&) <null> (envoy+0xb614ca4)
    #34 absl::Status std::__1::__invoke_void_return_wrapper<absl::Status>::__call<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14&, Envoy::Buffer::Instance&>(Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14&, Envoy::Buffer::Instance&) <null> (envoy+0xb614bd4)
    #35 std::__1::__function::__alloc_func<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14, std::__1::allocator<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14>, absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) <null> (envoy+0xb614b44)
    #36 std::__1::__function::__func<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14, std::__1::allocator<Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&)::$_14>, absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) <null> (envoy+0xb613173)
    #37 std::__1::__function::__value_func<absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) const <null> (envoy+0xbd8c9fb)
    #38 std::__1::function<absl::Status (Envoy::Buffer::Instance&)>::operator()(Envoy::Buffer::Instance&) const <null> (envoy+0xbd8044f)
    #39 Envoy::Http::Utility::exceptionToStatus(std::__1::function<absl::Status (Envoy::Buffer::Instance&)>, Envoy::Buffer::Instance&) <null> (envoy+0xbd6ad50)
    #40 Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&) <null> (envoy+0xb5f2e72)
    #41 virtual thunk to Envoy::Http::Legacy::Http1::ConnectionImpl::dispatch(Envoy::Buffer::Instance&) <null> (envoy+0xb5f302a)
    #42 Envoy::Http::ConnectionManagerImpl::onData(Envoy::Buffer::Instance&, bool) <null> (envoy+0xb531d15)
    #43 Envoy::Network::FilterManagerImpl::onContinueReading(Envoy::Network::FilterManagerImpl::ActiveReadFilter*, Envoy::Network::ReadBufferSource&) <null> (envoy+0xa7fe138)
    #44 Envoy::Network::FilterManagerImpl::onRead() <null> (envoy+0xa7fe65c)
    #45 Envoy::Network::ConnectionImpl::onRead(unsigned long) <null> (envoy+0xa7d0082)
    #46 Envoy::Network::ConnectionImpl::onReadReady() <null> (envoy+0xa7dc286)
    #47 Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) <null> (envoy+0xa7d7a2d)
    #48 Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6::operator()(unsigned int) const <null> (envoy+0xa7efea7)
    #49 decltype(std::__1::forward<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&>(fp)(std::__1::forward<unsigned int>(fp0))) std::__1::__invoke<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) <null> (envoy+0xa7efe1c)
    #50 void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int>(Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6&, unsigned int&&) <null> (envoy+0xa7efd4d)
    #51 std::__1::__function::__alloc_func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) <null> (envoy+0xa7efccd)
    #52 std::__1::__function::__func<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6, std::__1::allocator<Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::Dispatcher&, std::__1::unique_ptr<Envoy::Network::ConnectionSocket, std::__1::default_delete<Envoy::Network::ConnectionSocket> >&&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, Envoy::StreamInfo::StreamInfo&, bool)::$_6>, void (unsigned int)>::operator()(unsigned int&&) <null> (envoy+0xa7ee30c)
    #53 std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const <null> (envoy+0xa79fb14)
    #54 std::__1::function<void (unsigned int)>::operator()(unsigned int) const <null> (envoy+0xa79f638)
    #55 Envoy::Event::FileEventImpl::mergeInjectedEventsAndRunCb(unsigned int) <null> (envoy+0xa79c689)
    #56 Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_1::operator()(int, short, void*) const <null> (envoy+0xa79cb99)
    #57 Envoy::Event::FileEventImpl::assignEvents(unsigned int, event_base*)::$_1::__invoke(int, short, void*) <null> (envoy+0xa79c706)
    #58 event_persist_closure <null> (envoy+0xbe38dbf)
    #59 event_process_active_single_queue <null> (envoy+0xbe3770c)
    #60 event_process_active <null> (envoy+0xbe2c2c7)
    #61 event_base_loop <null> (envoy+0xbe29c7f)
    #62 Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) <null> (envoy+0xbe0055b)
    #63 Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) <null> (envoy+0xa7874f1)
    #64 Envoy::Server::InstanceImpl::run() <null> (envoy+0xa68d1c5)
    #65 Envoy::MainCommonBase::run() <null> (envoy+0x5659075)
    #66 Envoy::MainCommon::run() <null> (envoy+0x5660812)
    #67 Envoy::MainCommon::main(int, char**, std::__1::function<void (Envoy::Server::Instance&)>) <null> (envoy+0x5659fdd)
    #68 main <null> (envoy+0x5656415)
SUMMARY: ThreadSanitizer: data race (/home/.cache/bazel/_bazel_root/45ae47b4a0e12d1e81c831ece04d820d/execroot/io_istio_proxy/bazel-out/k8-fastbuild/bin/src/envoy/envoy+0x4fc5969) in __tsan_atomic32_fetch_add
==================
ThreadSanitizer: reported 1 warnings
2020/10/20 23:57:55 envoy process error: exit status 66
2020/10/20 23:57:55 stop envoy ... done
2020/10/20 23:57:55 stopping XDS server
```

**Pull request merged**
