### PR TITLE
Split JWT verification from forwarding logic.

### PR DESCRIPTION
**Pull request by nickrmc83**
**What this PR does / why we need it**:

This is the first PR in a set that will slowly introduce OpenID Connect end-user authentication and session management.
Splitting logic previously in jwt_authenticator into 2 parts.
- jwt_authenticator just contains logic for verifying/authenticating JWTs
- JWT forwarding logic has been moved into jwt_auth filter.

The changes enable greater re-usability of the JWT verification code across filters.
All tests updated and passing.

**Special notes for your reviewer**:

Envoy related PR: https://github.com/envoyproxy/envoy/pull/3428
Design discussions:
- https://docs.google.com/document/d/1oRoHt0iDBYRd_ETEtGJiNLhV1dKWMNgC6EvZAGmNcgk
- https://docs.google.com/document/d/1mGpUsRgmA9wPB73trfTiB9YUuwYh-31iulYg9USxe0Y

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by qiwzhang** [comment]
@nickrmc83 I am in the middle of porting jwt_authn code from Isito/proxy to Envoy.

Here is: https://github.com/envoyproxy/envoy/pull/3339

The jwt_authn code in istio/proxy is frozen now. 

I strongly suggest you make your change after I done the porting.   

If you don't want to wait,  you can create a private branch in istio/proxy to submit your change.  We may not have time to review it since it is in the private branch.

**Comment by nickrmc83** [comment]
@qiwzhang I'll wait until you've finished porting and then migrate the changes directly to envoy. I'll leave this PR open for the time being in case anyone wants to give some general feedback as what will appear in envoy will closely resemble these changes.

**Comment by dmadams** [comment]
Hi @nickrmc83 I was wondering where this was at. Are you still working on this? We are also interested in introducing OIDC to Envoy.

**Comment by nickrmc83** [comment]
Closing as the world has moved on as has the approach.

**Pull request closed without merging**
