### PR TITLE
Update common file, including license

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@PiotrSikora @howardjohn Any idea who manages circleci now? Looks like it might be our macos subscription expires.

**Comment by PiotrSikora** [comment]
I have no idea, sorry.

**Comment by howardjohn** [comment]
I think its @duderino

**Comment by bianpengyuan** [comment]
I created a https://github.com/istio/test-infra/pull/2298 to make macos test non-required temporarily to unblock PRs. @duderino Would you mind to help to set up the macos plan correctly?

**Comment by bianpengyuan** [comment]
Hmm.. Do I need to recreate the pr to make circleci non-required?

**Comment by bianpengyuan** [comment]
@clarketm ^^^

**Comment by howardjohn** [comment]
I think there is some delay, it may run every 30min or something? I just did the same thing

**Comment by clarketm** [comment]
> Hmm.. Do I need to recreate the pr to make circleci non-required?

Looks like the branchprotector is configured to run at 54 past the hour every hour ([ref](https://github.com/istio/test-infra/blob/51a74479f8696ae03106a4b7d63c6281c3219387/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml#L106)).

**Comment by bianpengyuan** [comment]
@kyessenov @PiotrSikora ptal, thanks!

**Pull request merged**
