### PR TITLE
feat(node_info): add cluster_id to node_info

### PR DESCRIPTION
**Pull request by douglas-reid**
Populate node_info from from `CLUSTER_ID` values in the envoy node metadata (and exchanged via metadata exchange).

This PR will enable cluster-focused telemetry allowing monitoring of cross-cluster traffic, etc. Users will be able to opt-in to stats dimensioned by cluster_id when so desired.

Related PRs:
- [x]  https://github.com/istio/istio/pull/22975
- [x] https://github.com/istio/istio/pull/23095

### CODE REVIEW

**Comment by mandarjog** [comment]
In single cluster deployments this seems like a waste, even though it gets us ready for multi cluster. Anything we can do?

**Comment by douglas-reid** [comment]
> In single cluster deployments this seems like a waste, even though it gets us ready for multi cluster. Anything we can do?

we could not include the labels when the cluster ids are `Kubernetes`.  Or we could make this an optional config that gets set in the envoyfilters when multicluster is enabled at install time or similar?  Thoughts?

**Comment by kyessenov** [comment]
1. Why doesn't OWNER field include the cluster in the URI?
2. It's fine to add a field and leave it unpopulated. It might cause slight perf cost due to regex.

**Comment by kyessenov** [comment]
I think you need to patch configurable metric desired output to include cluster labels.

**Comment by douglas-reid** [comment]
> 1. Why doesn't OWNER field include the cluster in the URI?

OWNER matches (for k8s) the kube resource URI, which doesn't include cluster name.

**Comment by mandarjog** [comment]
@douglas-reid or @bianpengyuan please check the tsan failure.

**Comment by bianpengyuan** [comment]
Not sure why connection is broken in the test. Probably should enable debugging log in CI to get better information.

**Comment by bianpengyuan** [comment]
Let me try to reproduce the test failure locally.

**Comment by bianpengyuan** [comment]
Let's skip if this rerun still does not work. I will spend some time to investigate.

**Comment by douglas-reid** [comment]
@bianpengyuan yeah, it all passes locally for me.

**Comment by nrjpoddar** [comment]
@douglas-reid can we make this optional instead of enabled by default?

**Comment by douglas-reid** [comment]
@nrjpoddar this is a topic for discussion tomorrow for this very reason.

**Comment by douglas-reid** [comment]
@kyessenov do we still need the node_info flatbuffer and context.cc parts of this PR, given that we are moving to opt-in with customizable metrics?  If not, I think I can close this entirely?

**Comment by kyessenov** [comment]
Yes, we do need the schema update for node info to make it available.

**Comment by douglas-reid** [comment]
@kyessenov OK. PTAL. I've removed all other bits of the PR.

**Pull request merged**
