### PR TITLE
fix location tag, update proto format

### PR DESCRIPTION
**Pull request by richardwxn**
1. location tag and url should be same line
2. location url should be placed together under proxy_extensions subdir
3. move position of next id block, otherwise it would be added to the doc.

### CODE REVIEW

**Comment by mandarjog** [comment]
@richardwxn you need to run ./scripts/check-style to ensure correct format.

**Comment by richardwxn** [comment]
@mandarjog Ok I fixed that, but actually the issue is that I we always need to add // clang-format off to the header part, otherwise the location tag line would be broken into two by the check-style script, which would make it fail to go to correct location in istio.io

**Comment by mandarjog** [comment]
I think it is ok to turn if off for that reason. 
Can we add a comment above that says why it is turned off? A subsequent PR is fine.

**Comment by mandarjog** [comment]
@richardwxn can you check why cherry pick is failing ?

**Comment by mandarjog** [comment]
@bianpengyuan @richardwxn has code diverged in 1.6 already ? It should not be .

**Comment by richardwxn** [comment]
@mandarjog actually not, the conflict is not related to the proto, but it is because git hard to resolve the conflicts in the comment section(edited header for the doc)

**Comment by richardwxn** [comment]
fyi https://github.com/istio/proxy/pull/2833 @mandarjog

**Pull request merged**
