### PR TITLE
Fix missing response size

### PR DESCRIPTION
**Pull request by kyessenov**
Manually verified:
```
istio_response_bytes_bucket{reporter="destination",source_workload="productpage-v1",source_workload_namespace="default",source_principal="unknown",source_app="productpage",source_version="v1",destination_workload="ratings-v1",destination_workload_namespace="default",destination_principal="unknown",destination_app="ratings",destination_version="v1",destination_service="server.default.svc.cluster.local",destination_service_name="server",destination_service_namespace="default",request_protocol="http",response_code="200",response_flags="-",connection_security_policy="NONE",permissive_response_code="none",permissive_response_policyid="none",le="+Inf"} 10
```

### CODE REVIEW

**Comment by kyessenov** [comment]
@howardjohn those are cherry-picks from envoy master to istio envoy 1.4.
CI is blocked on `go: google.golang.org/genproto@v0.0.0-20190819201941-24fa4b261c55: invalid $GOPROXY setting: cannot have comma`. Where is GOPROXY set and why there is a comma there?

**Comment by howardjohn** [comment]
Its in test-infra repo, caused by a recent change. We must be using and older go version (1.12) than the other repos here. Should be an easy fix.

**Comment by douglas-reid** [comment]
@kyessenov this includes the hardening PR, correct?

**Comment by mandarjog** [comment]
Yes it includes: https://github.com/istio/envoy/commit/b5c068ee2a087818f07b2dce0debd2de7983607e

**Comment by douglas-reid** [comment]
@mandarjog will this be cherry-picked against `master` and `release-1.5` too then?

**Pull request merged**
