### PR TITLE
Update Envoy SHA to cherry-pick fix for idle timer segfault.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Cherry-pick https://github.com/envoyproxy/envoy/pull/3970.

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Cherry-picked instead of rolling forward to minimize untested changes and to avoid picking https://github.com/envoyproxy/envoy/pull/3975, since it could require last minute changes in Pilot.

**Comment by rshriram** [comment]
Please wait. I have already merged the latest changes in istio (for latest Envoy sha). We can’t cherry pick because we need the gRPC bug fix.

**Comment by rshriram** [comment]
Sorry I spoke to soon. So we don’t need that fix because we don’t set the idle timer (ie disabled always). We set the stream_idle_timeout.

**Comment by rkpagadala** [comment]
@PiotrSikora I bumped the API because it was merged in release-1.0 branch, we need all the code to be consistent when shipped. Also it was a doc fix only. I would prefer not to merge this.

**Comment by lizan** [comment]
> Sorry I spoke to soon. So we don’t need that fix because we don’t set the idle timer (ie disabled always). We set the stream_idle_timeout. 

@rshriram If we set stream_idle_timeout, then it could trigger the segfault which fixed in envoyproxy/envoy#3970, when stream is created but envoy didn't get full request header, and idle timeout kicked in. @htuch correct me if I am wrong.

**Comment by costinm** [comment]
We were supposed to cut 1.0 30 min ago. 

I think it is too late. If it crashes we'll need to cut 1.0.1 next week

**Comment by htuch** [comment]
If you set it to zero, you are probably safe, otherwise you need to cherry
pick all follow-up PRs.

**Comment by rshriram** [comment]
See pilot code. It’s always set to 0 (stream idle timeout). But we don’t set idle timeout. 

And when we allow users to pick idle timeouts in future, we will be upgrading Envoy as well. Ie pull in bug fix automatically.

**Comment by PiotrSikora** [comment]
Superseded by #1894.

**Pull request closed without merging**
