### PR TITLE
Update envoy sha

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ramaraochavali — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@PiotrSikora Got a tsan failure on wee8 build (which is weird..) https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_proxy/3139/test-tsan_proxy/1347276088610394112/build-log.txt

Any idea about this? Does the same error happens in upstream and if so how did we fix it?

**Comment by bianpengyuan** [comment]
Unfortunately this is not a flake failure. Needs built image update.

**Review by jacob-delgado — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@shamsher31 build tools image has not been update in test infra. Tsan test will need the new image to pass, which contains https://github.com/istio/tools/pull/1390

**Comment by jacob-delgado** [comment]
cc @bianpengyuan Build tools have now been updated, I'm not sure if you'll need to rebase, but I think this should work.

**Comment by bianpengyuan** [comment]
Yeah I updated the sha again to match 1.17.0, but looks like test has build failure. Should be easy to fix and I am looking at it now.

**Comment by bianpengyuan** [comment]
@jacob-delgado Actually the build tools has not been updated: https://github.com/istio/test-infra/pull/3119

**Comment by jacob-delgado** [comment]
We will need to cherry-pick this into the release-1.9 branch. We are hoping to do this within the hour.

**Comment by jacob-delgado** [comment]
We are intending to branch around 7pm PST tonight due to various reasons; we had intended to branch this morning. If we can get this in before then that'd be easier, otherwise we can cherry-pick.

**Review by PiotrSikora — APPROVED** [review]

**Review by douglas-reid — APPROVED** [review]

**Comment by PiotrSikora** [comment]
@bianpengyuan this looks like a real issue, unfortunately:
```
WARNING: ThreadSanitizer: signal-unsafe call inside of a signal (pid=78339)
    #0 malloc <null> (envoy+0x51b1ec4)
    #1 operator new(unsigned long) <null> (libc++.so.1+0x86084)
    #2 std::__1::allocator<char>::allocate(unsigned long, void const*) <null> (envoy+0x5226cf4)
    #3 std::__1::allocator_traits<std::__1::allocator<char> >::allocate(std::__1::allocator<char>&, unsigned long) <null> (envoy+0x5226a6a)
    #4 fmt::v7::basic_memory_buffer<char, 250ul, std::__1::allocator<char> >::grow(unsigned long) <null> (envoy+0x5226581)
    #5 fmt::v7::detail::buffer<char>::reserve(unsigned long) <null> (envoy+0x522a600)
    #6 void fmt::v7::detail::buffer<char>::append<char>(char const*, char const*) <null> (envoy+0x522a392)
    #7 spdlog::details::fmt_helper::append_string_view(fmt::v7::basic_string_view<char>, fmt::v7::basic_memory_buffer<char, 250ul, std::__1::allocator<char> >&) <null> (envoy+0x5229dde)
    #8 spdlog::pattern_formatter::format(spdlog::details::log_msg const&, fmt::v7::basic_memory_buffer<char, 250ul, std::__1::allocator<char> >&) <null> (envoy+0x5224fd0)
    #9 Envoy::Logger::DelegatingLogSink::log(spdlog::details::log_msg const&) <null> (envoy+0xe66335c)
...
```

**Comment by bianpengyuan** [comment]
@PiotrSikora Yeah, that happened before I think, although it is from spdlog library, not sure what we can do..

**Comment by PiotrSikora** [comment]
@bianpengyuan the previous error was during V8 build because of a false-positive in `std::shared_ptr`, this is different.

**Comment by bianpengyuan** [comment]
@PiotrSikora Yeah, i knew. This tsan failure has been here for long time and happened occasionally. I somehow remembered that Kuat created an issue for this before, but cc @kyessenov to just to keep me honest here :)

**Pull request merged**
