### PR TITLE
Update Envoy-WASM SHA to latest with security fixes. (#2355)

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
> Why are we still pointing to https://github.com/envoyproxy/envoy-wasm/archive/ instead of https://github.com/istio/envoy/archive/???

Because release managers didn't update it yet?

On a side note: if we start pointing to commits in `istio/envoy:release-1.3`, then we cannot cherry-pick changes in [istio/proxy](https://github.com/istio/proxy) anymore, since the changes in `master` branch are going to be pointing at commits that don't exist in `istio/envoy:release-1.3`.

**Comment by rlenglet** [comment]
> Because release managers didn't update it yet?

My understanding is that release managers only manage the `release-1.3` branches.

**Comment by rlenglet** [comment]
I branched `release-1.3` out of `master`.

**Comment by rlenglet** [comment]
> On a side note: if we start pointing to commits in istio/envoy:release-1.3, then we cannot cherry-pick changes in istio/proxy anymore, since the changes in master branch are going to be pointing at commits that don't exist in istio/envoy:release-1.3.

I don't get your point. How can pointing `istio/proxy:release-1.3` to `istio/envoy:release-1.3` and `istio/proxy:master` to whatever your want create any problem?

**Comment by PiotrSikora** [comment]
> I don't get your point. How can pointing `istio/proxy:release-1.3` to `istio/envoy:release-1.3` and `istio/proxy:master` to whatever your want create any problem?

It's not a problem per-se, but problem for cherry-picks, since commit SHAs in `"whatever"` don't exist in `istio/envoy:release-1.3` (not for new commits), which means that commits updating Envoy SHA in `istio/proxy:master` cannot be cherry-picked into `istio/proxy:release-1.3`.

**Comment by rlenglet** [comment]
> It's not a problem per-se, but problem for cherry-picks, since commit SHAs in "whatever" don't exist in istio/envoy:release-1.3 (not for new commits), which means that commits updating Envoy SHA in istio/proxy:master cannot be cherry-picked into istio/proxy:release-1.3.

How are you suggesting to do otherwise, since you're supposed to only backport bug fixes for Istio 1.3? You can't just point to the latest master HEAD from `istio/proxy:release-1.3` every time you need to pick up a fix.

**Pull request merged**
