### PR TITLE
Bump Envoy SHA

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by howardjohn** [comment]
```
==> Summary
🍺  /usr/local/Cellar/git/2.28.0: 1,482 files, 48.5MB
Removing: /usr/local/Cellar/git/2.23.0_1... (1,543 files, 44.9MB)
==> Checking for dependents of upgraded formulae...
Error: No such file or directory - /usr/local/Cellar/git/2.23.0_1
```

is OSX known to be broken?

@PiotrSikora @jplevyak I think I recall one of you mention this?

**Comment by howardjohn** [comment]
Fixes https://github.com/istio/istio/issues/27698

**Comment by SecurityInsanity** [comment]
@howardjohn we talked about this in the 1.7.3/1.6.11 meeting, no one has ever seen OSX pass (in that meeting), and I believe @brian-avery was gonna add a working group item to talk about removing it?

**Review by SecurityInsanity — APPROVED** [review]

**Review by JimmyCYJ — APPROVED** [review]

**Pull request merged**
