### PR TITLE
Update envoy and update configs

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by wattli** [comment]
https://screenshot.googleplex.com/p1wmP0ic4Vi, some build error.

**Comment by lizan** [comment]
Working on that, seems some incompatibility with travis, jenkins passed.

**Comment by lizan** [comment]
Seems the issue with gcc 4.8, which travis uses, with gcc 4.9 there is no compile error. Working on a fix to that.

**Comment by wattli** [comment]
Thanks.

**Pull request merged**
