### PR TITLE
Use envoy_cc_library instead of cc_library

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Let me try to build it on my mac..

**Comment by PiotrSikora** [comment]
Why this change is sent against `release-1.5` and not against `master` with a cherry-pick label?

**Comment by bianpengyuan** [comment]
Yeah sorry, master fix: https://github.com/istio/proxy/pull/2722

**Comment by bianpengyuan** [comment]
The reason why this is not a cherry-pick from master is because the pr (https://github.com/istio/proxy/commit/d14ae10df125e1b26b6b770e5d8c8ccfc848af30) that causes build failure is only in release-1.5, not in master, since grpc library will have a more appropriate fix for that. So I sent the fix here first to fix the build.

**Comment by bianpengyuan** [comment]
@fpesce Mind approving this? This blocks 1.5 dev proxy build.

**Pull request merged**
