### PR TITLE
envoy: initial boilerplate/skeleton for metadata upstream

### PR DESCRIPTION
**Pull request by tbarrella**
**What this PR does / why we need it**:
Initial commit for https://github.com/istio/istio/issues/31444

Based on https://github.com/lambdai/envoy-dai/pull/7

**Special notes for your reviewer**:
I'd rather keep the commits small to make things easier to review. This is meant to be the smallest testable unit, establishing the code location and some naming

### CODE REVIEW

**Review by lambdai — CHANGES_REQUESTED** [review]
Nice move!

Can you add an integration test to prove that this upstream extension can be injected into the envoy cluster?

**Review by PiotrSikora — COMMENTED** [review]
Is there any reason why this is added to Istio Proxy and not Envoy itself?

**Comment by tbarrella** [comment]
> Nice move!
> 
> Can you add an integration test to prove that this upstream extension can be injected into the envoy cluster?

That can't be done yet. It will require a lot more code (connection pool, connection pool factory). I think that should be left for future PRs to keep size small

> Is there any reason why this is added to Istio Proxy and not Envoy itself?

I think adding this to Envoy would require aligning on an API that would be extensible enough to be used for needs in addition to just Istio. https://github.com/envoyproxy/envoy/issues/15472 is for discussing this. If that discussion blocked starting this, I don't think there would be time to finish this before Istio 1.10. This code would not include the extensible API, but just the headers that are needed for Istio (BTS, maybe temeletry)

**Review by lambdai — APPROVED** [review]
LGTM. Thanks!

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
Consensus from the offline discussion is to work on this upstream.

/hold

**Review by PiotrSikora — APPROVED** [review]
Apparently, Envoy doesn't want this.

**Pull request merged**
