### PR TITLE
Move mixerclient codes to proxy repo

### PR DESCRIPTION
**Pull request by qiwzhang**
**What this PR does / why we need it**:

This step is just move the code and make it pass the compiling and can build other components properly.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by lizan** [comment]
While I am fine with this change, is this repo re-organize discussed widely?

**Comment by qiwzhang** [comment]
Yes, I think during istio repo re-org.  It was decided that all c++ move into one repo.

**Comment by qiwzhang** [comment]
Here is the Istio repo reorg doc.
https://docs.google.com/document/d/1i1PEwx0vHCD9oR5vg1QJqo_8JfQFhwzOdIYarYdH1NI/edit#heading=h.x9snb54sjlu9

**Comment by qiwzhang** [comment]
It was decided all c++ code moved into one repo

**Comment by lizan** [comment]
/lgtm 

> We should probably also get rid of Bazel in here too at some point.
This will be hard and it is less benefit than that in istio/istio. Unless Envoy switches to another build toolchain. We don't even have a better alternative.

**Comment by ldemailly** [comment]
did you guys coordinate with test and release ?
(the sync bots and the release/build process are getting updated in this PR) ?

cc @hklai @rkpagadala @sebastienvas @mattdelco 

also next time please give a heads up to the oncall too

**Comment by ldemailly** [comment]
also looks like this isn't an import so you lost all history - please consider asking @mandarjog or anyone that helped with mono repo and redoing this migration properly

**Pull request merged**
