### PR TITLE
Set release managers as CODEOWNERS for release-1.3

### PR DESCRIPTION
**Pull request by rlenglet**
Setting up the release-1.3 branch, cf. https://github.com/istio/istio/issues/16201.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@rlenglet merging without the approval? *tsk* *tsk*

But the real complaint is that this was merged before the branch was supposed to be cut, and now the history is going to diverge a bit too early.

**Comment by rlenglet** [comment]
This had to be force-merged.

**Comment by rlenglet** [comment]
> But the real complaint is that this was merged before the branch was supposed to be cut, and now the history is going to diverge a bit too early.

My bad, I was expecting the `master` branch to be up-to-date.

**Comment by PiotrSikora** [comment]
It is, but I'm still adding the security fixes (per our talk on Monday).

**Pull request merged**
