### PR TITLE
stats: fix a typo and move callback for Wasm

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Address a couple of issues found by https://github.com/istio/istio/pull/41991.
 * typo in `BlackHoleCluster`
 * Wasm filters incorrectly set filter state in `log()`, move to that for compatibility.

### CODE REVIEW

**Review by lei-tang — APPROVED** [review]

**Comment by lei-tang** [comment]
LGTM. Added a do-not-merge label so zirain can have a chance to take a look before the PR is merged.

**Comment by zirain** [comment]
@kyessenov need backport?

**Review by zirain — APPROVED** [review]
/lgtm

**Comment by zirain** [comment]
test-asan normal finished in 30m, but sometimes it stuck for more than 1h.

**Pull request merged**
