### PR TITLE
Manual update of common-files for proxy

### PR DESCRIPTION
**Pull request by ericvn**
**What this PR does / why we need it**:

This job is a manual update of the common-files. The automated update was inadvertently removed in a test-infra job and has since been re-added. Either the stranded automated job, https://github.com/istio/proxy/pull/3785, will get updated with the next common-files update (after the test-infra PR is merged), or this can be merged to manually update.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Comment by ericvn** [comment]
Seems like we have the 
```
stackdriver_test.go:952: listen tcp :23005: bind: address already in use
```
error happening more often now. I had noted earlier this seems to have maybe started happening around the change to Golang 1.18.0.

**Pull request merged**
