### PR TITLE
network filter: set identiy from PROXY TLV header

### PR DESCRIPTION
**Pull request by stevenctl**
**What this PR does / why we need it**:

This is the most basic filter for propagating identity from the sandwich 

// TODO link the zTunnel PR here that sets the TLV header

**Which issue this PR fixes** 

First step towards https://github.com/istio/istio/issues/48362

**Special notes for your reviewer**:

This uses 0xD0 as the key for the spiffe string. We could support multiple formats here, e.g.

0xD0 -> SPIFFE string directly into peer_principal
0XD1 -> A JWT that also sets some metadata

### CODE REVIEW

**Review by kyessenov — CHANGES_REQUESTED** [review]
Do we really need a new filter? Can we use set_filter_state filter to copy TLV record from ProxyProto filter state into the principal? I thought someone has already accomplished this upstream.

**Comment by stevenctl** [comment]
How can we grab one element of [tlv_vector](https://github.com/envoyproxy/envoy/blob/4f0965e9c61f8daa3519dc0298d4833cf8730307/envoy/network/proxy_protocol.h#L22) matching the "type" byte using that API?

**Comment by stevenctl** [comment]
I could not get the `on_tlv_present -> some other key -> set_filter_state(%FILTER_STATE(thatotherkey)%)` working. Will provide yaml to reproduce this.

**Comment by stevenctl** [comment]
Not a standalone yaml, but grabbed some from configdumps:

On the listener it's this and http inspector:

```
            listener_filters:
              - name: envoy.filters.listener.proxy_protocol
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
                  rules:
                    - tlv_type: 208
                      on_tlv_present:
                        key: peer_principal
                  pass_through_tlvs:
                    tlv_type:
                      - 208
```

And then before HCM I have

```
                  - name: proxy_protocol_authority
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.network.set_filter_state.v3.Config
                      on_new_connection:
                        - object_key: io.istio.peer_principal
                          format_string:
                            text_format_source:
                              inline_string: '%DYNAMIC_METADATA(envoy.filters.listener.proxy_protocol:peer_principal)%'
                          shared_with_upstream: ONCE
```

**Comment by kyessenov** [comment]
Is it because `on_new_connection` is called too early? Can you check from trace logs? If so, we might need another trigger for `onEvent`.

**Comment by kyessenov** [comment]
Also, `set_filter_state` needs to be on the same listener as proxy proto handler.

**Comment by stevenctl** [comment]
Set_filter_state is working now. I'm not sure what I was doing wrong originally.. possibly unrelated to set filter state or maybe I had one of the connect_authority ones in there before?

**Pull request closed without merging**
