### PR TITLE
Fill response flag for stats plugin

### PR DESCRIPTION
**Pull request by bianpengyuan**
This needs https://github.com/istio/envoy/pull/116 to be in to work with 1.4 and envoyproxy/envoy-wasm to be updated to work with master.

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Can I get some review on this? Thanks!

**Comment by bianpengyuan** [comment]
@kyessenov Does this look like the a flake to you? It seems to be different from client timeout we saw before. There is no crashes and does not return any mismatches.. so likely the prometheus endpoint does not return metrics. Could this also happen because of staled listeners?

```
--- FAIL: TestStatsParallel (48.68s)
    stats_xds_test.go:233: failed to match all stats
FAIL
FAIL	istio.io/proxy/test/envoye2e/stats	66.504s
ok  	istio.io/proxy/test/envoye2e/stats_plugin	23.067s
ok  	istio.io/proxy/test/envoye2e/tcp_metadata_exchange	5.045s
Makefile.core.mk:79: recipe for target 'test_tsan' failed
make: *** [test_tsan] Error 1
```

**Comment by kyessenov** [comment]
@bianpengyuan Yeah this is not a timeout. Either prometheus reports incorrect stats, or we failed to report one. Does this happen consistently? We can disable the test for now to get this in.

**Comment by bianpengyuan** [comment]
@kyessenov haven't retried it. Let me retest it.

**Comment by kyessenov** [comment]
I noticed that it was polling stats endpoint for ~20s. I think it was just starved of CPU resources since TSAN builds are slow.

**Pull request merged**
