### PR TITLE
feat(metric): add istio_build metric to prom stats at config time

### PR DESCRIPTION
**Pull request by douglas-reid**
This adds the `istio_build` metric back to the proxy.

This is a revert of #2473, which was a revert of #2431.

### CODE REVIEW

**Comment by douglas-reid** [comment]
@bianpengyuan PTAL. I added a test.

**Comment by bianpengyuan** [comment]
Looks like go format fails: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_proxy/2575/test_proxy/249/build-log.txt

**Comment by douglas-reid** [comment]
@bianpengyuan unfortunately, it doesn't not fail when I run `BUILD_WITH_CONTAINER=1 make lint` so i'm a bit of a loss on how to debug.

**Comment by bianpengyuan** [comment]
Retest passed format checking. Looks like go-fmt is flaky.

**Pull request merged**
