### PR TITLE
fix(edges): remove unknown defaults 

### PR DESCRIPTION
**Pull request by douglas-reid**
**What this PR does / why we need it**:
Manual cherry-pick of #2592 .

### CODE REVIEW

**Comment by mandarjog** [comment]
All 3 builds timed out.

**Comment by howardjohn** [comment]
will merge after 1.4.2

**Comment by douglas-reid** [comment]
/test proxy-presubmit-asan

building chrome timed out.

**Comment by douglas-reid** [comment]
@howardjohn time to merge?

**Pull request merged**
