### PR TITLE
wasm: remove stats and attributegen from the tree

### PR DESCRIPTION
**Pull request by kyessenov**
After the switch to the native stats, we no longer need to maintain the v8 version of the same extension. However, we should continue exercising Wasm-related code in Envoy, to make sure ABI is backwards compatible.

This PR deletes the code for Wasm versions of attributegen and stats from the tree. It preserves the tests for those modules fixed at the version of the last SHA artifacts. We also enable TSan and Asan for more of the Wasm-related tests to gain more confidence in Wasm filter in Envoy.

### CODE REVIEW

**Comment by zirain** [comment]
should update related doc？

**Comment by kyessenov** [comment]
@zirain Yeah, https://github.com/istio/istio.io/pull/12765

**Review by zirain — APPROVED** [review]
LGTM, should put this into upgrade notes.

**Comment by ericvn** [comment]
@kyessenov The post-submit proxy code is failing now. I suspect something here.
```
Pushing Wasm OCI image for stats
+ bazel run --local_ram_resources=12288 --local_cpu_resources=8 --verbose_failures --test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=errors --google_default_credentials --remote_instance_name=projects/istio-testing/instances/default_instance --remote_cache=grpcs://remotebuildexecution.googleapis.com --config=libc++ --stamp --config=debug //extensions:push_wasm_image_stats
[32mINFO: [0mInvocation ID: e4b620a3-2cb9-4b91-9794-5420c4b74651
[32mLoading:[0m
[32mLoading:[0m 0 packages loaded
[31m[1mERROR: [0mSkipping '//extensions:push_wasm_image_stats': no such target '//extensions:push_wasm_image_stats': target 'push_wasm_image_stats' not declared in package 'extensions' defined by /home/prow/go/src/istio.io/proxy/extensions/BUILD (Tip: use `query "//extensions:*"` to see all the targets in that package)
[35mWARNING: [0mTarget pattern parsing failed.
[31m[1mERROR: [0mno such target '//extensions:push_wasm_image_stats': target 'push_wasm_image_stats' not declared in package 'extensions' defined by /home/prow/go/src/istio.io/proxy/extensions/BUILD (Tip: use `query "//extensions:*"` to see all the targets in that package)
[32mINFO: [0mElapsed time: 0.611s
[32mINFO: [0m0 processes.
[31m[1mFAILED:[0m Build did NOT complete successfully (0 packages loaded)
[31m[1mERROR: [0mBuild failed. Not running target
[0m+ rm -rf /tmp/wasm-plugins-TK8KjpKIig
Makefile.core.mk:194: recipe for target 'push_release' failed
make: *** [push_release] Error 1
```

**Comment by ericvn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/release_proxy_postsubmit/1628852690580672512

**Comment by kyessenov** [comment]
@ericvn Thanks, missed an instance https://github.com/istio/proxy/pull/4467.

**Pull request merged**
