### PR TITLE
release: fixed missed location for `${ARCH_SUFFIX}`

### PR DESCRIPTION
**Pull request by howardjohn**
Note: currently testing this internally for now but this will be part of standard CI, I hope, soon in OSS

### CODE REVIEW

**Review by kyessenov — COMMENTED** [review]
Do you plan to add pre-submit for ARM as well? Envoy has a lot of arch-dependent code so it's not safe to release something we don't test in pre-submit.

**Comment by howardjohn** [comment]
Yep. We don't yet have an ARM cluster (should be in ~1 week), but once we have that we can

**Comment by kyessenov** [comment]
We'll need ARM tests here as well.

**Comment by howardjohn** [comment]
Yes that is what I mean. We will have istio/proxy ARM tests.

**Review by kyessenov — APPROVED** [review]

**Pull request merged**
