### PR TITLE
StatefulSession: include HeaderBasedSessionState extension

### PR DESCRIPTION
**Pull request by Pawan-Bishnoi**
**What this PR does / why we need it**:
This PR includes a newly added extension for stateful sessions `envoy.extensions.http.stateful_session.header.v3.HeaderBasedSessionState`

**Special notes for your reviewer**:
This is the envoy PR : https://github.com/envoyproxy/envoy/pull/23145/files

### CODE REVIEW

**Comment by deveshkandpal1224** [comment]
@howardjohn @zirain - can you please review / approve this PR ? Thanks.

**Comment by ramaraochavali** [comment]
@lei-tang @howardjohn can you PTAL?

**Review by lei-tang — COMMENTED** [review]
Why does this extension need to be added to istio/proxy? Any use cases for this extension in istio/proxy?

**Comment by ramaraochavali** [comment]
> Why does this extension need to be added to istio/proxy? Any use cases for this extension in istio/proxy?

Yes.  We already support cookie based stateful session in Istio via https://github.com/istio/istio/pull/42592. There is an agreement to support header based in follow-up. See comments from [here](https://github.com/istio/istio/pull/42592#issuecomment-1378827248).  There is an ongoing [PR](https://github.com/istio/istio/pull/42840) to support that.

**Review by lei-tang — APPROVED** [review]

**Pull request merged**
