### PR TITLE
Add flag indicating current semantics of report batch

### PR DESCRIPTION
**Pull request by douglas-reid**
**What this PR does / why we need it**:

* Sets the `RepeatedAttributesSemantics` for `ReportRequests` (needed to address deletions in batches)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

https://github.com/istio/istio/issues/11151

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kyessenov** [comment]
Unit test failing. Please adjust the test to take the semantics into account.

**Comment by douglas-reid** [comment]
@kyessenov yup. guilty. :flushed:

**Comment by kyessenov** [comment]
@wenchenglu Please merge. This is needed to fix the linked bug.

**Pull request merged**
