### PR TITLE
Add local rate limiting wasm filter

### PR DESCRIPTION
**Pull request by gargnupur**
Signed-off-by: gargnupur <gargnupur@google.com>

**What this PR does / why we need it**:
Adds local rate limiting wasm filter

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by bianpengyuan — COMMENTED** [review]
Can we do it in Wasm ecosystem repo: https://github.com/istio-ecosystem/wasm-extensions if this is going to be Wasm only plugin?

**Comment by kyessenov** [comment]
I think it makes sense to make it Wasm-only. Rate limiting has a wide range of requirements, so this would be a good example. Since I don't think one-size-fits-all solution, it is not useful to compile in.

We can also simplify the build there, and drop the extra cruft with protos.

**Comment by kyessenov** [comment]
It's really important to measure performance hit for this filter. We should not add too much overhead at a very high rate limit.

**Comment by gargnupur** [comment]
@kyessenov , @bianpengyuan : Thanks, will add this to istio-ecosystem repo and add benchmark perf tests too..

**Comment by kyessenov** [comment]
Merged into wasm-extensions.

**Pull request closed without merging**
