### PR TITLE
Release 1.4 codeowners

### PR DESCRIPTION
**Pull request by ericvn**
Set release managers as code owners and update the common-files.

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Note: this should have repointed Envoy repo from `envoyproxy/envoy-wasm` to `istio/envoy` and update to the commit from `release-1.4` branch.

**Comment by PiotrSikora** [comment]
Reverting to old version of common files broke postsubmit, btw.

**Comment by PiotrSikora** [comment]
@istio/release-managers-1-4 can you guys fix the 2 aforementioned issues?

**Comment by howardjohn** [comment]
Working on it

**Pull request merged**
