### PR TITLE
Update Envoy-WASM SHA to latest with HTTP inspector fixes.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Pulling in istio/envoy#120.

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by rshriram** [comment]
Why is this getting an exception when the ALS one is not? Shouldn't we wait until we decide on what to do about the proxy version (basing off envoy stable or master) ?

**Comment by PiotrSikora** [comment]
@rshriram this is a security fix.

**Comment by PiotrSikora** [comment]
@rshriram can you remove the `do-not-merge` label, since it's blocking merge and the release?

**Comment by howardjohn** [comment]
I think @rshriram 's discussion is reasonable, but we should not block the release on this

**Comment by rshriram** [comment]
My point is that we have a very buggy ALS system in 1.4 release today. And fixes for those are not allowed because of deviation from the baseline release. So why is this ? We could turn off sniffing (we already do) in inbound. So, this might as well wait for an entire release ?

**Comment by PiotrSikora** [comment]
@rshriram the whole point of stable releases of Envoy and using them in Istio Proxy is to support bugfixes such as the ALS one. I don't recall anybody not allowing it to be cherry-picked...

**Comment by lizan** [comment]
@PiotrSikora @rshriram yeah sure let's cherry-pick, PTAL istio/envoy#121

**Pull request merged**
