### PR TITLE
deflake: bump connect timeout for slow builds

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by douglas-reid** [comment]
just curious: is the bump based on data?  or is this more "i know it is slow. this will hopefully help?"

**Comment by kyessenov** [comment]
Yes, I saw connect timeout after 1s in the debug logs on CI.

**Review by douglas-reid — APPROVED** [review]

**Pull request merged**
