### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by zirain**
fixes: https://github.com/istio/proxy/pull/4631

### CODE REVIEW

**Comment by zirain** [comment]
/retest

looks like a flaky

**Comment by kyessenov** [comment]
Something is wonky in prometheus output:
```stats_test.go:521: text format parsing error in line 155: second TYPE line for metric name "envoy_cluster_assignment_stale", or TYPE reported after samples```

**Comment by kyessenov** [comment]
Probably related to https://github.com/envoyproxy/envoy/pull/24998, but I'm not seeing anything wrong in the envoy output manually.

**Comment by zirain** [comment]
> Probably related to [envoyproxy/envoy#24998](https://github.com/envoyproxy/envoy/pull/24998), but I'm not seeing anything wrong in the envoy output manually.

yeah, seems like some space or tab char error

**Comment by zirain** [comment]
wait https://github.com/envoyproxy/envoy/issues/27173

**Review by kyessenov — APPROVED** [review]

**Pull request merged**
