### PR TITLE
Remove wasm binary file

### PR DESCRIPTION
**Pull request by bianpengyuan**
**What this PR does / why we need it**:
This pr removes wasm binary file from here to avoid frequent merge conflict. Instead the file is generated in ci and wasm related test will run after that. Wasm file will still be pushed to gcs in postsubmit.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@mandarjog @gargnupur @douglas-reid fyi.

**Comment by kyessenov** [comment]
Can you add `.gitignore` for the wasm files?

**Comment by bianpengyuan** [comment]
unlike to be a successful cherry-pick though..

**Comment by kyessenov** [comment]
Yeah, I know, but let's see what the bot says.

**Pull request merged**
