### PR TITLE
build: remove wasm metadata exchange

### PR DESCRIPTION
**Pull request by kyessenov**
Code will move to istio-ecosystem/wasm-extensions for archiving.

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Will this proy be landed on 1.20, then we will already repalce it with native filter

**Comment by zirain** [comment]
> Will this proy be landed on 1.20, then we will already repalce it with native filter

see https://github.com/istio/istio/pull/46498

**Comment by ericvn** [comment]
See https://github.com/istio/istio/pull/46517 for a change since this is no longer being built.

**Pull request merged**
