### PR TITLE
build: support Envoy native Bazel build.

### PR DESCRIPTION
**Pull request by htuch**
This patch switches the Envoy build from src/envoy/repositories.bzl to
using the upstream native build.

See https://github.com/lyft/envoy/pull/663 for the corresponding changes
on the Envoy side.

### CODE REVIEW

**Comment by htuch** [comment]
@lizan @wattli This is pointing at my private branch for Envoy right now, once https://github.com/lyft/envoy/pull/663 is merged I an update to lyft/envoy.

**Comment by lizan** [comment]
LGTM, can you merge envoy change then update this PR, also you need clang-format 3.8.0 to comply with `script/check-style`.

**Comment by lizan** [comment]
jenkins: test this

**Comment by sebastienvas** [comment]
jenkins please build proxy/presubmit

**Comment by sebastienvas** [comment]
jenkins please build proxy/presubmit

**Pull request merged**
