### PR TITLE
revert of https://github.com/istio/proxy/pull/2591

### PR DESCRIPTION
**Pull request by kyessenov**

### CODE REVIEW

**Comment by kyessenov** [comment]
Please see https://github.com/istio/istio/wiki/Configurable-V2-Metrics how to add dimensions via configuration.

**Comment by lambdai** [comment]
@yxue Please confirm

**Comment by yxue** [comment]
If user could configure the dimension in 1.5, I think it's OK to revert the PR.

**Comment by kyessenov** [comment]
@yxue @lambdai If you are OK using configuration to add a dimensions for analysis purposes, can you one of you please approve. I'd like to cherry pick this into 1.5.

**Pull request merged**
