### PR TITLE
Optimize Referenced::Signature function

### PR DESCRIPTION
**Pull request by qiwzhang**
**What this PR does / why we need it**:

Optimize signature calculation code.  It is based on https://github.com/istio/proxy/pull/1562
But fix the code format.

**Special notes for your reviewer**:

```release-note
None
```

### CODE REVIEW

**Comment by qiwzhang** [comment]
@skyao please review this change. I just use this PR to fix your code format problem

**Comment by skyao** [comment]
@qiwzhang Thank you very mush! I have reviewed the code, no problem.

Please go ahead, and let's see if some performance increase after this fixing.

**Comment by qiwzhang** [comment]
Unfortunately, master branch is locked.  We have to wait for it to open

**Comment by qiwzhang** [comment]
Decided to check into release-0.8 branch with https://github.com/istio/proxy/pull/1742

**Comment by skyao** [comment]
@qiwzhang I saw this issue and also issue #1742 are closed, but seems the code is not merged. What happened?

**Comment by qiwzhang** [comment]
Change is in with https://github.com/istio/proxy/pull/1751.

**Pull request closed without merging**
