### PR TITLE
fix and deflake SD reload test

### PR DESCRIPTION
**Pull request by bianpengyuan**
Several changes to SD reload test:
* In https://github.com/istio/proxy/pull/2780, [the last revision](https://github.com/istio/proxy/pull/2780/commits/f4ceb426f525f9c1f80afec1d02694db047614d8) actually makes test not verify vm reload. This PR makes it so that VM id is modified with lds version, which will really trigger a VM reload.
* Make SD listener reload test only update listener config once. Even two config updates could make test flaky, so lower it to update only once.
* Skip both SD listener reload test and vm reload test when ASan/TSan due to known flake caused by slowness.

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@kyessenov ptal, thanks! Test in last pr is not verifying vm reload because of a bad revision. This PR fix it.

**Comment by kyessenov** [comment]
Ok, I was concerned that we don't actually test reloads, so wanted some indication that without the fix the reloads are broken.

**Comment by bianpengyuan** [comment]
Yeah the last revision actually revokes verification of VM reload. Sorry about that :p. For this PR I've for sure tested the latest commit would fail without onDone logic.

**Pull request merged**
