### PR TITLE
Update sha to include https://github.com/istio/envoy/pull/263

### PR DESCRIPTION
**Pull request by incfly**
istio/istio#25909 for release 1.6.

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Review by lambdai — COMMENTED** [review]
Thank you for the chaining update!

Approve in terms of networking

CC @istio/release-managers-1-6

**Review by brian-avery — APPROVED** [review]
Approving this and adding a do-not-merge label. We can merge after Tuesday's release.

**Comment by incfly** [comment]
@brian-avery do you think it's ready to be merged?

**Comment by incfly** [comment]
Proceed as 1.6.11 is out already.

**Pull request merged**
