### PR TITLE
Update envoy to latest

### PR DESCRIPTION
**Pull request by lizan**
**What this PR does / why we need it**:

- Support bazel 0.10

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by ldemailly** [comment]
hmmm it doesn't build:
```
W0208 22:58:43.076] ERROR: /home/bootstrap/go/src/github.com/istio/proxy/src/envoy/mixer/BUILD:23:1: C++ compilation of rule '//src/envoy/mixer:filter_lib' failed (Exit 1).
W0208 22:58:43.077] src/envoy/mixer/utils.cc: In function 'bool Envoy::Http::Utils::GetIpPort(const Envoy::Network::Address::Ip*, std::__cxx11::string*, int*)':
W0208 22:58:43.078] src/envoy/mixer/utils.cc:61:57: error: conversion from 'absl::uint128' to non-scalar type 'std::array<unsigned char, 16ul>' requested
W0208 22:58:43.079]        std::array<uint8_t, 16> ipv6 = ip->ipv6()->address();
W0208 22:58:43.079]                                                          ^
```

**Comment by ashutosh-narkar** [comment]
I get this error:
`Successful build of /root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/boringssl.dep
make: Leaving directory '/root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/external/envoy_deps'
DEBUG: /root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/external/envoy/bazel/repositories.bzl:84:5: External dep build exited with return code: 1
DEBUG: /root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/external/envoy/bazel/repositories.bzl:86:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
ERROR: /root/.cache/bazel/_bazel_root/99befe685ff48e352428f1d9cabb5dd7/external/envoy/bazel/repositories.bzl:169:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'
ERROR: Analysis of target '//src/envoy:envoy' failed; build aborted: Loading failed
INFO: Elapsed time: 196.799s
FAILED: Build did NOT complete successfully (14 packages loaded)`

**Pull request merged**
