### PR TITLE
Use envoy-wasm as upstream

### PR DESCRIPTION
**Pull request by bianpengyuan**

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@kyessenov Seems like prow overlooks your approve?

**Comment by kyessenov** [comment]
@utka any hints how to kick tide to re-process this PR? it seems like it missed some success notifications from circle and cla bots.

**Comment by bianpengyuan** [comment]
I can recreate one if that is easier.

**Comment by kyessenov** [comment]
Close/open sometimes does the trick.

**Comment by bianpengyuan** [comment]
Still says review required. Let me recreated one then.

**Comment by utka** [comment]
I saw it today with another PR, that tide got stuck. Let me check the logs

**Comment by bianpengyuan** [comment]
@utka Thanks! Fyi I recreated https://github.com/istio/proxy/pull/2252, not sure if it could pass the tide check.

**Pull request closed without merging**
