### PR TITLE
Revert STS changes from release-1.4

### PR DESCRIPTION
**Pull request by duderino**
@bianpengyuan @PiotrSikora I'm rolling back the istio/proxy changes to the point I think before we started making STS changes.   After this goes through, I will send an additional PR to pull in the istio/envoy release-1.4 HEAD and also one commit from @PiotrSikora from the private repo

### CODE REVIEW

**Comment by bianpengyuan** [comment]
#2721 and #2719 are bug fixes unrelated to sts. They should not be reverted.

**Comment by duderino** [comment]
> #2721 and #2719 are bug fixes unrelated to sts. They should not be reverted.

Are there commits I can exclude from the revert?

**Comment by bianpengyuan** [comment]
Yeah, these two PRs should just be excluded from this revert: #2721 and #2719

**Comment by duderino** [comment]
Apologies @bianpengyuan @kyessenov @PiotrSikora when I reverted my reverts of @bianpengyuan's two PRs I pushed to the wrong branch.   Can I get an after the fact approval on this one?

**Comment by duderino** [comment]
Specifically, this is what istio/proxy:release-1.4 looks like, which I think is the right state:

```
commit f9187298a5027c3763815eee159c58b417843923 (HEAD, upstream/release-1.4, release-1.4)
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Thu Mar 5 09:45:02 2020 -0800

    Revert "Revert "Set ticker in onConfigure instead of onStart (#2721)""
    
    This reverts commit 60fdc7852dd1b70bc7779f10af39a8cea54b9679.

commit 151ef0a6a15e46b1470e6e9e516cea829dc39c88
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Thu Mar 5 09:44:43 2020 -0800

    Revert "Revert "feat(edges): support configurable batch size (#2707) (#2719)""
    
    This reverts commit 28e323c163362d61dff265a9d6203a259643b94b.

commit 7bd6c08cdd10a53f203a16c3a75f299b71f7f155 (origin/release-1.4)
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Wed Mar 4 13:06:58 2020 -0800

    Revert "[release-1.4] Add sts to sd filter (#2679)"
    
    This reverts commit 4e98e0b3c061b9ec3fb6e02a61aea6f4d148cc91.

commit 7e9f1fb8ec0af5bac9d76fd8be23143fb58b1465
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Wed Mar 4 13:06:56 2020 -0800

    Revert "update proxy sha (#2694)"
    
    This reverts commit afe6a81b5e13011ff578ad2518173a5e955b82d7.

commit 7bad8b962c29dd74487e11005e515af1ea6061ce
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Wed Mar 4 13:06:55 2020 -0800

    Revert "Fix node metadata fetch in stackdriver filter (#2683)"
    
    This reverts commit 15dd15b8096cf767aa9b9e5ca745e24792e1a2e2.

commit 28e323c163362d61dff265a9d6203a259643b94b
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Wed Mar 4 13:06:53 2020 -0800

    Revert "feat(edges): support configurable batch size (#2707) (#2719)"
    
    This reverts commit 4ad74d676aea80d578ba9b3f7e2e24b7f2960768.

commit 60fdc7852dd1b70bc7779f10af39a8cea54b9679
Author: Joshua Blatt <jtblatt@gmail.com>
Date:   Wed Mar 4 13:06:48 2020 -0800

    Revert "Set ticker in onConfigure instead of onStart (#2721)"
    
    This reverts commit 5e9c866f7e7198d5119347b3d06dceb6e29f4715.
```

**Pull request merged**
