### PR TITLE
Update envoy to 07c2bf9

### PR DESCRIPTION
**Pull request by lizan**
**What this PR does / why we need it**:
Update envoy to https://github.com/envoyproxy/envoy/commit/07c2bf971c147e45326cccaa65e5843c9484ae6c

- Use AsyncClientFactory in gRPC transport.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
Please resolve the conflicting files. http_filter.cc is split into smaller files now.

**Comment by qiwzhang** [comment]
I am working on a separate PR to place these changes on top of new code.

**Comment by lizan** [comment]
@qiwzhang I merged master, also mind this change requires prow images update (to pick bazel 0.11) so I'll work on that.

**Pull request merged**
