### PR TITLE
bazel: add extensions config

### PR DESCRIPTION
**Pull request by lambdai**
Disable tcp_stats and add mysql_proxy 
Signed-off-by: Yuchen Dai <silentdai@gmail.com>

### CODE REVIEW

**Comment by anuragagarwal561994** [comment]
`envoy.transport_sockets.tcp_stats` how do we enable this if one wants to?

**Comment by zirain** [comment]
it's enabled.
https://github.com/istio/proxy/blob/ff99990ec25610e697462d78c741e624ca2640dc/bazel/extension_config/extensions_build_config.bzl#L256

**Comment by anuragagarwal561994** [comment]
@zirain it is disabled https://github.com/istio/proxy/blob/ff99990ec25610e697462d78c741e624ca2640dc/bazel/extension_config/extensions_build_config.bzl#L485

**Comment by zirain** [comment]
so, you cannot use it without a custom proxy build.

**Comment by anuragagarwal561994** [comment]
As per the disucssion I followed, it was done because some of the kernel versions hindered with this filter and as per the above conversation a different binary was may be expected to be released where these would be applicable.

Are the above conditions still valid based on the latest linux versions and the base image being used and is there any plan to support a custom build with this extension enabled?

**Comment by zirain** [comment]
AFAIK, there isn't a plan about this.
need context about why should istio do that? is it a common use case?

**Comment by anuragagarwal561994** [comment]
@zirain so the idea is we wanted to track metrics for how much rtt time is spent between envoy to upstream and envoy to downstream.

To do so we wanted to expose these metrics, it is available in the envoyproxy but then because of the custom build of enovy in istio this is currently not possible.

I tried using envoyproxy without the custom version but then istio specific customisations like `metadata-exchange` extension is missing.

I tried building do a custom build of envoy, but now to build it I am using

```
docker run -it --rm -w /work -v $PWD:/work gcr.io/istio-testing/build-tools-proxy:master-latest bash
> make build_envoy
```

But the base image is using ubuntu bionic which doesn't support the required kernel for correct tcp.h and hence the build is failing. I think upgrading the base image should be able to solve the issue, so trying to now figure this out. I wanted to know if there is an easier way.

**Pull request merged**
