### PR TITLE
Always use Bazel-0.25 for macOS on CircleCI (release-1.2).

### PR DESCRIPTION
**Pull request by PiotrSikora**
Backported from #2252.

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@duderino ping.

**Comment by PiotrSikora** [comment]
@bianpengyuan sure, updated... But the point of this PR is to pin Bazel on macOS, otherwise it was installing the latest version on each CI run and completely breaking `ci/circleci: macos`.

**Comment by bianpengyuan** [comment]
@PiotrSikora I see. Thanks!

**Comment by duderino** [comment]
One of the 1.2 release managers should handle this one: @fpesce @linsun

**Comment by silentdai** [comment]
istio/ci:go1.11-bazel0.25-clang7-cmake3.8.0 is accessible at linux so hopefully in macOS it is also reachable.

I don't have a mac to test but it looks good to me

/lgtm

**Comment by PiotrSikora** [comment]
@silentdai macOS doesn't use Docker, but always installs Bazel 0.25.0. Tests pass on CircleCi, btw.

**Pull request merged**
