### PR TITLE
Update Envoy dependency to support transparent listeners

### PR DESCRIPTION
**Pull request by rlenglet**
Use a version of Envoy that implements transparent listen sockets (https://github.com/envoyproxy/envoy/pull/2719).

Related: https://github.com/istio/istio/pull/4651
Required by: https://github.com/istio/istio/pull/4654

Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
I signed it!

**Comment by rlenglet** [comment]
Please note that this PR can't be merged yet. It is blocked on https://github.com/envoyproxy/envoy/pull/2719 getting merged first. However, I'd like to get early feedback on this if possible.

**Comment by rlenglet** [comment]
https://github.com/envoyproxy/envoy/pull/2719 was merged upstream into Envoy. Updated this PR to pick the upstream commit.

**Comment by lizan** [comment]
Please sign the CLA. LGTM otherwise.

**Comment by rlenglet** [comment]
@lizan I already signed the LCA. Thanks!

**Pull request merged**
