### PR TITLE
Add request host header to metric dimension.

### PR DESCRIPTION
**Pull request by bianpengyuan**
Add request host header to metric tag. It follows `use_host_header` option, and set to `unknown` when host header fallback is disabled.

@jshaughn

ref: https://github.com/istio/istio/issues/21820

### CODE REVIEW

**Comment by douglas-reid** [comment]
It feels like we should follow the rough policy that we followed with the other additions for this release:

- add the information so that it is readily available
- add the dimension to the bootstrap config so that it can easily be used
- document how to add it to metrics w/ configurable metrics functionality

Then once we see how it works, etc., decide on adding it to the default set.

**Comment by kyessenov** [comment]
There is a spot to document stats extensions https://github.com/istio/istio.io/pull/7137.
We can make it more concrete by enumerating various use cases (SNI, request_host, request_operation, multi cluster).

**Comment by bianpengyuan** [comment]
Ok thanks! Make a lot of sense. Then the right change is to add the additional tag to bootstrap instead of doing it here. I will close this one then.

**Comment by bianpengyuan** [comment]
@kyessenov sg, I will add it here.

**Pull request closed without merging**
