### PR TITLE
Update travis to support go.

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by lizan** [comment]
Why do we need this? bazel pulls go dependencies automatically, the go in travis VM system path is not used at all.

**Comment by lizan** [comment]
If you're trying to fix https://travis-ci.org/istio/proxy/builds/219424878 , this one is not travis specific, it is reproducible on local.

**Comment by qiwzhang** [comment]
It is a blind shot.  I have no clue what caused this failure.
https://travis-ci.org/istio/proxy/builds/219425806

**Comment by qiwzhang** [comment]
I guess my local is polluted. It did not happen in my local.  Jenkins is fine too.

**Comment by lizan** [comment]
bazel team renamed https://github.com/bazelbuild/buildifier to https://github.com/bazelbuild/buildtools , some archive download path are no longer working, your local and jenkins have the downloaded zip cached.

**Comment by lizan** [comment]
https://github.com/bazelbuild/rules_go/issues/361

**Comment by qiwzhang** [comment]
Is there anything we can do to fix it?  or just wait for them to fix it?

**Comment by lizan** [comment]
I posted a quick fix https://github.com/bazelbuild/rules_go/pull/363 , we need to wait them to merge it.

**Comment by lizan** [comment]
Upgrade rules_go to latest master should solve this. @qiwzhang

**Pull request closed without merging**
