### PR TITLE
Going back to 3b05bff

### PR DESCRIPTION
**Pull request by rshriram**
Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

### CODE REVIEW

**Comment by rshriram** [comment]
and thank you for the daily words of wisdom

**Comment by kyessenov** [comment]
@rshriram In istio repo, place your experimental envoy into `~/go/out/linux...` directory and run all the tests locally. The build is not checking that dependencies match, so it will take whatever envoy you throw at it. You then go debug the memory leak locally, instead of using shared test infra.

**Comment by rshriram** [comment]
Oh! Thats a nice idea.. Will try.. We should document it in readme or something

**Comment by rshriram** [comment]
/hold
We finally found the memory leak and fixed it. I also validated with Istio e2e tests. Waiting for envoy PR to be merged.

**Pull request closed without merging**
