### PR TITLE
updated envoy sha to latest, required for enabling zone aware routing

### PR DESCRIPTION
**Pull request by GregHanson**
**What this PR does / why we need it**:
 required for enabling zone aware routing

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by rkpagadala** [comment]
@GregHanson should this go in release-0.8 or in master?

**Comment by rshriram** [comment]
release 0.8.. This fixes a long standing bug with zone aware routing

**Comment by qiwzhang** [comment]
I am working on a separate PR to get the latest Envoy sha,  fixing some compiling errors and a test failure.

**Comment by qiwzhang** [comment]
I will close this one once my PR is ready

**Pull request closed without merging**
